-- core.model_library seed / refresh
-- Generated by scripts/seed-models.mjs on 2026-07-19
-- Allowlist verified_at: 2026-07-19
--
-- Rates are nanos per 1M tokens (1 nano = 1e-9 USD). cached_* is the cache-READ
-- price. Rows marked "tier: upper" are context-tiered models seeded at the HIGHER
-- rate — see tiering_note in the allowlist.
--
-- ON CONFLICT DO UPDATE: refresh corrects drift. Operator-added rows absent from
-- the allowlist are never touched.

-- source: https://platform.claude.com/docs/en/about-claude/pricing.md
INSERT INTO core.model_library (uid, provider, model_id, context_cap_tokens, input_nanos_per_mtok, cached_input_nanos_per_mtok, output_nanos_per_mtok, created_at_ms, updated_at_ms) VALUES (
  '079e4ab8-86e5-7c63-839b-b7ea6e1c5817', 'anthropic', 'claude-opus-4-8', 1000000, 5000000000, 500000000, 25000000000, 1784419200000, 1784419200000)
ON CONFLICT (provider, model_id) DO UPDATE SET
  context_cap_tokens = EXCLUDED.context_cap_tokens, input_nanos_per_mtok = EXCLUDED.input_nanos_per_mtok,
  cached_input_nanos_per_mtok = EXCLUDED.cached_input_nanos_per_mtok, output_nanos_per_mtok = EXCLUDED.output_nanos_per_mtok,
  updated_at_ms = EXCLUDED.updated_at_ms;

-- source: https://platform.claude.com/docs/en/about-claude/pricing.md
INSERT INTO core.model_library (uid, provider, model_id, context_cap_tokens, input_nanos_per_mtok, cached_input_nanos_per_mtok, output_nanos_per_mtok, created_at_ms, updated_at_ms) VALUES (
  '2772a21f-5ca7-7d0a-8a0b-701a83b8dec9', 'anthropic', 'claude-sonnet-5', 1000000, 3000000000, 300000000, 15000000000, 1784419200000, 1784419200000)
ON CONFLICT (provider, model_id) DO UPDATE SET
  context_cap_tokens = EXCLUDED.context_cap_tokens, input_nanos_per_mtok = EXCLUDED.input_nanos_per_mtok,
  cached_input_nanos_per_mtok = EXCLUDED.cached_input_nanos_per_mtok, output_nanos_per_mtok = EXCLUDED.output_nanos_per_mtok,
  updated_at_ms = EXCLUDED.updated_at_ms;

-- source: https://platform.claude.com/docs/en/about-claude/pricing.md
INSERT INTO core.model_library (uid, provider, model_id, context_cap_tokens, input_nanos_per_mtok, cached_input_nanos_per_mtok, output_nanos_per_mtok, created_at_ms, updated_at_ms) VALUES (
  'ee9ac081-5761-7aed-8605-5cd28fb90443', 'anthropic', 'claude-fable-5', 1000000, 10000000000, 1000000000, 50000000000, 1784419200000, 1784419200000)
ON CONFLICT (provider, model_id) DO UPDATE SET
  context_cap_tokens = EXCLUDED.context_cap_tokens, input_nanos_per_mtok = EXCLUDED.input_nanos_per_mtok,
  cached_input_nanos_per_mtok = EXCLUDED.cached_input_nanos_per_mtok, output_nanos_per_mtok = EXCLUDED.output_nanos_per_mtok,
  updated_at_ms = EXCLUDED.updated_at_ms;

-- source: https://platform.claude.com/docs/en/about-claude/pricing.md
INSERT INTO core.model_library (uid, provider, model_id, context_cap_tokens, input_nanos_per_mtok, cached_input_nanos_per_mtok, output_nanos_per_mtok, created_at_ms, updated_at_ms) VALUES (
  'f0431e92-1dfe-7bac-889d-0a7101ff66ac', 'anthropic', 'claude-haiku-4-5', 200000, 1000000000, 100000000, 5000000000, 1784419200000, 1784419200000)
ON CONFLICT (provider, model_id) DO UPDATE SET
  context_cap_tokens = EXCLUDED.context_cap_tokens, input_nanos_per_mtok = EXCLUDED.input_nanos_per_mtok,
  cached_input_nanos_per_mtok = EXCLUDED.cached_input_nanos_per_mtok, output_nanos_per_mtok = EXCLUDED.output_nanos_per_mtok,
  updated_at_ms = EXCLUDED.updated_at_ms;

-- source: https://developers.openai.com/api/docs/pricing
INSERT INTO core.model_library (uid, provider, model_id, context_cap_tokens, input_nanos_per_mtok, cached_input_nanos_per_mtok, output_nanos_per_mtok, created_at_ms, updated_at_ms) VALUES (
  '676c6536-a29f-7e66-8fef-39f8563681e3', 'openai', 'gpt-5.6-sol', 1050000, 5000000000, 500000000, 30000000000, 1784419200000, 1784419200000)
ON CONFLICT (provider, model_id) DO UPDATE SET
  context_cap_tokens = EXCLUDED.context_cap_tokens, input_nanos_per_mtok = EXCLUDED.input_nanos_per_mtok,
  cached_input_nanos_per_mtok = EXCLUDED.cached_input_nanos_per_mtok, output_nanos_per_mtok = EXCLUDED.output_nanos_per_mtok,
  updated_at_ms = EXCLUDED.updated_at_ms;

-- source: https://developers.openai.com/api/docs/pricing
INSERT INTO core.model_library (uid, provider, model_id, context_cap_tokens, input_nanos_per_mtok, cached_input_nanos_per_mtok, output_nanos_per_mtok, created_at_ms, updated_at_ms) VALUES (
  'd9b4ebfc-2b59-7c15-8050-0e96e07b5c0c', 'openai', 'gpt-5.6-terra', 1050000, 2500000000, 250000000, 15000000000, 1784419200000, 1784419200000)
ON CONFLICT (provider, model_id) DO UPDATE SET
  context_cap_tokens = EXCLUDED.context_cap_tokens, input_nanos_per_mtok = EXCLUDED.input_nanos_per_mtok,
  cached_input_nanos_per_mtok = EXCLUDED.cached_input_nanos_per_mtok, output_nanos_per_mtok = EXCLUDED.output_nanos_per_mtok,
  updated_at_ms = EXCLUDED.updated_at_ms;

-- source: https://developers.openai.com/api/docs/pricing
INSERT INTO core.model_library (uid, provider, model_id, context_cap_tokens, input_nanos_per_mtok, cached_input_nanos_per_mtok, output_nanos_per_mtok, created_at_ms, updated_at_ms) VALUES (
  '65d2134d-0dfc-71b0-84dd-8a90277dda75', 'openai', 'gpt-5.6-luna', 1050000, 1000000000, 100000000, 6000000000, 1784419200000, 1784419200000)
ON CONFLICT (provider, model_id) DO UPDATE SET
  context_cap_tokens = EXCLUDED.context_cap_tokens, input_nanos_per_mtok = EXCLUDED.input_nanos_per_mtok,
  cached_input_nanos_per_mtok = EXCLUDED.cached_input_nanos_per_mtok, output_nanos_per_mtok = EXCLUDED.output_nanos_per_mtok,
  updated_at_ms = EXCLUDED.updated_at_ms;

-- source: https://developers.openai.com/api/docs/pricing
INSERT INTO core.model_library (uid, provider, model_id, context_cap_tokens, input_nanos_per_mtok, cached_input_nanos_per_mtok, output_nanos_per_mtok, created_at_ms, updated_at_ms) VALUES (
  'cbb9c7a8-e88d-76c3-875d-0c216f7ca9bb', 'openai', 'gpt-5.5-pro', 1050000, 30000000000, 30000000000, 180000000000, 1784419200000, 1784419200000)
ON CONFLICT (provider, model_id) DO UPDATE SET
  context_cap_tokens = EXCLUDED.context_cap_tokens, input_nanos_per_mtok = EXCLUDED.input_nanos_per_mtok,
  cached_input_nanos_per_mtok = EXCLUDED.cached_input_nanos_per_mtok, output_nanos_per_mtok = EXCLUDED.output_nanos_per_mtok,
  updated_at_ms = EXCLUDED.updated_at_ms;

-- source: https://developers.openai.com/api/docs/pricing
INSERT INTO core.model_library (uid, provider, model_id, context_cap_tokens, input_nanos_per_mtok, cached_input_nanos_per_mtok, output_nanos_per_mtok, created_at_ms, updated_at_ms) VALUES (
  '90835ec2-a3eb-715b-8d8b-a1ef766c76b6', 'openai', 'gpt-5.3-codex', 400000, 1750000000, 175000000, 14000000000, 1784419200000, 1784419200000)
ON CONFLICT (provider, model_id) DO UPDATE SET
  context_cap_tokens = EXCLUDED.context_cap_tokens, input_nanos_per_mtok = EXCLUDED.input_nanos_per_mtok,
  cached_input_nanos_per_mtok = EXCLUDED.cached_input_nanos_per_mtok, output_nanos_per_mtok = EXCLUDED.output_nanos_per_mtok,
  updated_at_ms = EXCLUDED.updated_at_ms;

-- gemini/gemini-3.1-pro-preview: upper tier seeded (see allowlist)
-- source: https://ai.google.dev/gemini-api/docs/pricing
INSERT INTO core.model_library (uid, provider, model_id, context_cap_tokens, input_nanos_per_mtok, cached_input_nanos_per_mtok, output_nanos_per_mtok, created_at_ms, updated_at_ms) VALUES (
  '4ac8c032-1b1e-718e-8073-4845abe74cef', 'gemini', 'gemini-3.1-pro-preview', 1048576, 4000000000, 400000000, 18000000000, 1784419200000, 1784419200000)
ON CONFLICT (provider, model_id) DO UPDATE SET
  context_cap_tokens = EXCLUDED.context_cap_tokens, input_nanos_per_mtok = EXCLUDED.input_nanos_per_mtok,
  cached_input_nanos_per_mtok = EXCLUDED.cached_input_nanos_per_mtok, output_nanos_per_mtok = EXCLUDED.output_nanos_per_mtok,
  updated_at_ms = EXCLUDED.updated_at_ms;

-- source: https://ai.google.dev/gemini-api/docs/pricing
INSERT INTO core.model_library (uid, provider, model_id, context_cap_tokens, input_nanos_per_mtok, cached_input_nanos_per_mtok, output_nanos_per_mtok, created_at_ms, updated_at_ms) VALUES (
  'd1d419e2-959d-762f-84bf-291735ac5b88', 'gemini', 'gemini-3.5-flash', 1048576, 1500000000, 150000000, 9000000000, 1784419200000, 1784419200000)
ON CONFLICT (provider, model_id) DO UPDATE SET
  context_cap_tokens = EXCLUDED.context_cap_tokens, input_nanos_per_mtok = EXCLUDED.input_nanos_per_mtok,
  cached_input_nanos_per_mtok = EXCLUDED.cached_input_nanos_per_mtok, output_nanos_per_mtok = EXCLUDED.output_nanos_per_mtok,
  updated_at_ms = EXCLUDED.updated_at_ms;

-- source: https://ai.google.dev/gemini-api/docs/pricing
INSERT INTO core.model_library (uid, provider, model_id, context_cap_tokens, input_nanos_per_mtok, cached_input_nanos_per_mtok, output_nanos_per_mtok, created_at_ms, updated_at_ms) VALUES (
  'a9e6fdfe-1cce-7e66-8bc2-3c4b7bcec6b3', 'gemini', 'gemini-3.1-flash-lite', 1048576, 250000000, 25000000, 1500000000, 1784419200000, 1784419200000)
ON CONFLICT (provider, model_id) DO UPDATE SET
  context_cap_tokens = EXCLUDED.context_cap_tokens, input_nanos_per_mtok = EXCLUDED.input_nanos_per_mtok,
  cached_input_nanos_per_mtok = EXCLUDED.cached_input_nanos_per_mtok, output_nanos_per_mtok = EXCLUDED.output_nanos_per_mtok,
  updated_at_ms = EXCLUDED.updated_at_ms;

-- source: https://api-docs.deepseek.com/quick_start/pricing
INSERT INTO core.model_library (uid, provider, model_id, context_cap_tokens, input_nanos_per_mtok, cached_input_nanos_per_mtok, output_nanos_per_mtok, created_at_ms, updated_at_ms) VALUES (
  'f4451003-5c81-7b01-86a3-69f4ba0d74e2', 'deepseek', 'deepseek-v4-pro', 1000000, 435000000, 3625000, 870000000, 1784419200000, 1784419200000)
ON CONFLICT (provider, model_id) DO UPDATE SET
  context_cap_tokens = EXCLUDED.context_cap_tokens, input_nanos_per_mtok = EXCLUDED.input_nanos_per_mtok,
  cached_input_nanos_per_mtok = EXCLUDED.cached_input_nanos_per_mtok, output_nanos_per_mtok = EXCLUDED.output_nanos_per_mtok,
  updated_at_ms = EXCLUDED.updated_at_ms;

-- source: https://api-docs.deepseek.com/quick_start/pricing
INSERT INTO core.model_library (uid, provider, model_id, context_cap_tokens, input_nanos_per_mtok, cached_input_nanos_per_mtok, output_nanos_per_mtok, created_at_ms, updated_at_ms) VALUES (
  '81804932-7933-7448-831d-f8e86820edee', 'deepseek', 'deepseek-v4-flash', 1000000, 140000000, 2800000, 280000000, 1784419200000, 1784419200000)
ON CONFLICT (provider, model_id) DO UPDATE SET
  context_cap_tokens = EXCLUDED.context_cap_tokens, input_nanos_per_mtok = EXCLUDED.input_nanos_per_mtok,
  cached_input_nanos_per_mtok = EXCLUDED.cached_input_nanos_per_mtok, output_nanos_per_mtok = EXCLUDED.output_nanos_per_mtok,
  updated_at_ms = EXCLUDED.updated_at_ms;

-- source: https://platform.kimi.ai/docs/pricing/chat-k3
INSERT INTO core.model_library (uid, provider, model_id, context_cap_tokens, input_nanos_per_mtok, cached_input_nanos_per_mtok, output_nanos_per_mtok, created_at_ms, updated_at_ms) VALUES (
  '0c266877-fd66-781b-822c-41d7535e3b99', 'kimi', 'kimi-k3', 1048576, 3000000000, 300000000, 15000000000, 1784419200000, 1784419200000)
ON CONFLICT (provider, model_id) DO UPDATE SET
  context_cap_tokens = EXCLUDED.context_cap_tokens, input_nanos_per_mtok = EXCLUDED.input_nanos_per_mtok,
  cached_input_nanos_per_mtok = EXCLUDED.cached_input_nanos_per_mtok, output_nanos_per_mtok = EXCLUDED.output_nanos_per_mtok,
  updated_at_ms = EXCLUDED.updated_at_ms;

-- source: https://platform.kimi.ai/docs/pricing/chat-k3
INSERT INTO core.model_library (uid, provider, model_id, context_cap_tokens, input_nanos_per_mtok, cached_input_nanos_per_mtok, output_nanos_per_mtok, created_at_ms, updated_at_ms) VALUES (
  '1b03bcf0-9680-74fd-8683-dc0ab7e9a091', 'kimi', 'kimi-k2.7-code', 262144, 950000000, 190000000, 4000000000, 1784419200000, 1784419200000)
ON CONFLICT (provider, model_id) DO UPDATE SET
  context_cap_tokens = EXCLUDED.context_cap_tokens, input_nanos_per_mtok = EXCLUDED.input_nanos_per_mtok,
  cached_input_nanos_per_mtok = EXCLUDED.cached_input_nanos_per_mtok, output_nanos_per_mtok = EXCLUDED.output_nanos_per_mtok,
  updated_at_ms = EXCLUDED.updated_at_ms;

-- source: https://platform.kimi.ai/docs/pricing/chat-k3
INSERT INTO core.model_library (uid, provider, model_id, context_cap_tokens, input_nanos_per_mtok, cached_input_nanos_per_mtok, output_nanos_per_mtok, created_at_ms, updated_at_ms) VALUES (
  'dcb2e371-dab3-7ef0-8eb2-686070bf788b', 'kimi', 'kimi-k2.7-code-highspeed', 262144, 1900000000, 380000000, 8000000000, 1784419200000, 1784419200000)
ON CONFLICT (provider, model_id) DO UPDATE SET
  context_cap_tokens = EXCLUDED.context_cap_tokens, input_nanos_per_mtok = EXCLUDED.input_nanos_per_mtok,
  cached_input_nanos_per_mtok = EXCLUDED.cached_input_nanos_per_mtok, output_nanos_per_mtok = EXCLUDED.output_nanos_per_mtok,
  updated_at_ms = EXCLUDED.updated_at_ms;

-- source: https://docs.z.ai/guides/overview/pricing
INSERT INTO core.model_library (uid, provider, model_id, context_cap_tokens, input_nanos_per_mtok, cached_input_nanos_per_mtok, output_nanos_per_mtok, created_at_ms, updated_at_ms) VALUES (
  '4079508e-a630-7dff-8ce8-0579b826b061', 'glm', 'glm-5.2', 1000000, 1400000000, 260000000, 4400000000, 1784419200000, 1784419200000)
ON CONFLICT (provider, model_id) DO UPDATE SET
  context_cap_tokens = EXCLUDED.context_cap_tokens, input_nanos_per_mtok = EXCLUDED.input_nanos_per_mtok,
  cached_input_nanos_per_mtok = EXCLUDED.cached_input_nanos_per_mtok, output_nanos_per_mtok = EXCLUDED.output_nanos_per_mtok,
  updated_at_ms = EXCLUDED.updated_at_ms;

-- minimax/MiniMax-M3: upper tier seeded (see allowlist)
-- source: https://platform.minimax.io/docs/guides/pricing-paygo
INSERT INTO core.model_library (uid, provider, model_id, context_cap_tokens, input_nanos_per_mtok, cached_input_nanos_per_mtok, output_nanos_per_mtok, created_at_ms, updated_at_ms) VALUES (
  '09341fb9-eb86-7eab-8845-aa5e412ae5d0', 'minimax', 'MiniMax-M3', 1000000, 600000000, 120000000, 2400000000, 1784419200000, 1784419200000)
ON CONFLICT (provider, model_id) DO UPDATE SET
  context_cap_tokens = EXCLUDED.context_cap_tokens, input_nanos_per_mtok = EXCLUDED.input_nanos_per_mtok,
  cached_input_nanos_per_mtok = EXCLUDED.cached_input_nanos_per_mtok, output_nanos_per_mtok = EXCLUDED.output_nanos_per_mtok,
  updated_at_ms = EXCLUDED.updated_at_ms;

-- source: https://www.alibabacloud.com/help/en/model-studio/model-pricing
INSERT INTO core.model_library (uid, provider, model_id, context_cap_tokens, input_nanos_per_mtok, cached_input_nanos_per_mtok, output_nanos_per_mtok, created_at_ms, updated_at_ms) VALUES (
  '73c8121f-0393-78f2-8f3d-bbe73240605f', 'qwen', 'qwen3.7-max', 1000000, 2500000000, 250000000, 7500000000, 1784419200000, 1784419200000)
ON CONFLICT (provider, model_id) DO UPDATE SET
  context_cap_tokens = EXCLUDED.context_cap_tokens, input_nanos_per_mtok = EXCLUDED.input_nanos_per_mtok,
  cached_input_nanos_per_mtok = EXCLUDED.cached_input_nanos_per_mtok, output_nanos_per_mtok = EXCLUDED.output_nanos_per_mtok,
  updated_at_ms = EXCLUDED.updated_at_ms;

-- xai/grok-4.5: upper tier seeded (see allowlist)
-- source: https://docs.x.ai/docs/pricing
INSERT INTO core.model_library (uid, provider, model_id, context_cap_tokens, input_nanos_per_mtok, cached_input_nanos_per_mtok, output_nanos_per_mtok, created_at_ms, updated_at_ms) VALUES (
  '77c3f0ea-cb26-7c71-8af7-12008f4b77e9', 'xai', 'grok-4.5', 500000, 4000000000, 600000000, 12000000000, 1784419200000, 1784419200000)
ON CONFLICT (provider, model_id) DO UPDATE SET
  context_cap_tokens = EXCLUDED.context_cap_tokens, input_nanos_per_mtok = EXCLUDED.input_nanos_per_mtok,
  cached_input_nanos_per_mtok = EXCLUDED.cached_input_nanos_per_mtok, output_nanos_per_mtok = EXCLUDED.output_nanos_per_mtok,
  updated_at_ms = EXCLUDED.updated_at_ms;

-- xai/grok-4.3: upper tier seeded (see allowlist)
-- source: https://docs.x.ai/docs/pricing
INSERT INTO core.model_library (uid, provider, model_id, context_cap_tokens, input_nanos_per_mtok, cached_input_nanos_per_mtok, output_nanos_per_mtok, created_at_ms, updated_at_ms) VALUES (
  '90637595-2e55-73a1-8c77-467d0890c352', 'xai', 'grok-4.3', 1000000, 2500000000, 400000000, 5000000000, 1784419200000, 1784419200000)
ON CONFLICT (provider, model_id) DO UPDATE SET
  context_cap_tokens = EXCLUDED.context_cap_tokens, input_nanos_per_mtok = EXCLUDED.input_nanos_per_mtok,
  cached_input_nanos_per_mtok = EXCLUDED.cached_input_nanos_per_mtok, output_nanos_per_mtok = EXCLUDED.output_nanos_per_mtok,
  updated_at_ms = EXCLUDED.updated_at_ms;

-- source: https://groq.com/pricing
INSERT INTO core.model_library (uid, provider, model_id, context_cap_tokens, input_nanos_per_mtok, cached_input_nanos_per_mtok, output_nanos_per_mtok, created_at_ms, updated_at_ms) VALUES (
  '475db732-901e-7508-8f0d-40c32a31a569', 'groq', 'openai/gpt-oss-120b', 131072, 150000000, 75000000, 600000000, 1784419200000, 1784419200000)
ON CONFLICT (provider, model_id) DO UPDATE SET
  context_cap_tokens = EXCLUDED.context_cap_tokens, input_nanos_per_mtok = EXCLUDED.input_nanos_per_mtok,
  cached_input_nanos_per_mtok = EXCLUDED.cached_input_nanos_per_mtok, output_nanos_per_mtok = EXCLUDED.output_nanos_per_mtok,
  updated_at_ms = EXCLUDED.updated_at_ms;

-- source: https://groq.com/pricing
INSERT INTO core.model_library (uid, provider, model_id, context_cap_tokens, input_nanos_per_mtok, cached_input_nanos_per_mtok, output_nanos_per_mtok, created_at_ms, updated_at_ms) VALUES (
  '86d5d986-f04e-7a6e-8e70-d394e8a592de', 'groq', 'openai/gpt-oss-20b', 131072, 75000000, 37500000, 300000000, 1784419200000, 1784419200000)
ON CONFLICT (provider, model_id) DO UPDATE SET
  context_cap_tokens = EXCLUDED.context_cap_tokens, input_nanos_per_mtok = EXCLUDED.input_nanos_per_mtok,
  cached_input_nanos_per_mtok = EXCLUDED.cached_input_nanos_per_mtok, output_nanos_per_mtok = EXCLUDED.output_nanos_per_mtok,
  updated_at_ms = EXCLUDED.updated_at_ms;

-- source: https://mistral.ai/pricing/api
INSERT INTO core.model_library (uid, provider, model_id, context_cap_tokens, input_nanos_per_mtok, cached_input_nanos_per_mtok, output_nanos_per_mtok, created_at_ms, updated_at_ms) VALUES (
  'ce5b2092-1fa7-76e2-8f8c-be7e0dfbf0c9', 'mistral', 'mistral-medium-latest', 256000, 1500000000, 150000000, 7500000000, 1784419200000, 1784419200000)
ON CONFLICT (provider, model_id) DO UPDATE SET
  context_cap_tokens = EXCLUDED.context_cap_tokens, input_nanos_per_mtok = EXCLUDED.input_nanos_per_mtok,
  cached_input_nanos_per_mtok = EXCLUDED.cached_input_nanos_per_mtok, output_nanos_per_mtok = EXCLUDED.output_nanos_per_mtok,
  updated_at_ms = EXCLUDED.updated_at_ms;

-- source: https://mistral.ai/pricing/api
INSERT INTO core.model_library (uid, provider, model_id, context_cap_tokens, input_nanos_per_mtok, cached_input_nanos_per_mtok, output_nanos_per_mtok, created_at_ms, updated_at_ms) VALUES (
  '3ecac487-41ad-7773-807a-5ad48e256874', 'mistral', 'mistral-large-latest', 256000, 500000000, 50000000, 1500000000, 1784419200000, 1784419200000)
ON CONFLICT (provider, model_id) DO UPDATE SET
  context_cap_tokens = EXCLUDED.context_cap_tokens, input_nanos_per_mtok = EXCLUDED.input_nanos_per_mtok,
  cached_input_nanos_per_mtok = EXCLUDED.cached_input_nanos_per_mtok, output_nanos_per_mtok = EXCLUDED.output_nanos_per_mtok,
  updated_at_ms = EXCLUDED.updated_at_ms;

-- source: https://mistral.ai/pricing/api
INSERT INTO core.model_library (uid, provider, model_id, context_cap_tokens, input_nanos_per_mtok, cached_input_nanos_per_mtok, output_nanos_per_mtok, created_at_ms, updated_at_ms) VALUES (
  '3f92c27f-d190-795c-8ad5-bdf55601c9b1', 'mistral', 'mistral-small-latest', 256000, 150000000, 15000000, 600000000, 1784419200000, 1784419200000)
ON CONFLICT (provider, model_id) DO UPDATE SET
  context_cap_tokens = EXCLUDED.context_cap_tokens, input_nanos_per_mtok = EXCLUDED.input_nanos_per_mtok,
  cached_input_nanos_per_mtok = EXCLUDED.cached_input_nanos_per_mtok, output_nanos_per_mtok = EXCLUDED.output_nanos_per_mtok,
  updated_at_ms = EXCLUDED.updated_at_ms;

-- source: https://mistral.ai/pricing/api
INSERT INTO core.model_library (uid, provider, model_id, context_cap_tokens, input_nanos_per_mtok, cached_input_nanos_per_mtok, output_nanos_per_mtok, created_at_ms, updated_at_ms) VALUES (
  '29b93e3a-7f92-76e7-8ede-fe94e926776d', 'mistral', 'devstral-medium-latest', 256000, 400000000, 40000000, 2000000000, 1784419200000, 1784419200000)
ON CONFLICT (provider, model_id) DO UPDATE SET
  context_cap_tokens = EXCLUDED.context_cap_tokens, input_nanos_per_mtok = EXCLUDED.input_nanos_per_mtok,
  cached_input_nanos_per_mtok = EXCLUDED.cached_input_nanos_per_mtok, output_nanos_per_mtok = EXCLUDED.output_nanos_per_mtok,
  updated_at_ms = EXCLUDED.updated_at_ms;

-- source: https://mistral.ai/pricing/api
INSERT INTO core.model_library (uid, provider, model_id, context_cap_tokens, input_nanos_per_mtok, cached_input_nanos_per_mtok, output_nanos_per_mtok, created_at_ms, updated_at_ms) VALUES (
  '62dc745b-762b-74a2-81a2-06925bdfa280', 'mistral', 'codestral-latest', 128000, 300000000, 30000000, 900000000, 1784419200000, 1784419200000)
ON CONFLICT (provider, model_id) DO UPDATE SET
  context_cap_tokens = EXCLUDED.context_cap_tokens, input_nanos_per_mtok = EXCLUDED.input_nanos_per_mtok,
  cached_input_nanos_per_mtok = EXCLUDED.cached_input_nanos_per_mtok, output_nanos_per_mtok = EXCLUDED.output_nanos_per_mtok,
  updated_at_ms = EXCLUDED.updated_at_ms;

-- source: https://api.pioneer.ai/base-models
INSERT INTO core.model_library (uid, provider, model_id, context_cap_tokens, input_nanos_per_mtok, cached_input_nanos_per_mtok, output_nanos_per_mtok, created_at_ms, updated_at_ms) VALUES (
  '4b55e492-840d-78bb-83e8-a618d6bf3e51', 'pioneer', 'claude-opus-4-8', 1000000, 5500000000, 550000000, 27500000000, 1784419200000, 1784419200000)
ON CONFLICT (provider, model_id) DO UPDATE SET
  context_cap_tokens = EXCLUDED.context_cap_tokens, input_nanos_per_mtok = EXCLUDED.input_nanos_per_mtok,
  cached_input_nanos_per_mtok = EXCLUDED.cached_input_nanos_per_mtok, output_nanos_per_mtok = EXCLUDED.output_nanos_per_mtok,
  updated_at_ms = EXCLUDED.updated_at_ms;

-- source: https://api.pioneer.ai/base-models
INSERT INTO core.model_library (uid, provider, model_id, context_cap_tokens, input_nanos_per_mtok, cached_input_nanos_per_mtok, output_nanos_per_mtok, created_at_ms, updated_at_ms) VALUES (
  'fa0a13b1-fbaa-7e6b-8c9a-40313f2966cb', 'pioneer', 'claude-sonnet-5', 1000000, 2000000000, 200000000, 10000000000, 1784419200000, 1784419200000)
ON CONFLICT (provider, model_id) DO UPDATE SET
  context_cap_tokens = EXCLUDED.context_cap_tokens, input_nanos_per_mtok = EXCLUDED.input_nanos_per_mtok,
  cached_input_nanos_per_mtok = EXCLUDED.cached_input_nanos_per_mtok, output_nanos_per_mtok = EXCLUDED.output_nanos_per_mtok,
  updated_at_ms = EXCLUDED.updated_at_ms;

-- source: https://api.pioneer.ai/base-models
INSERT INTO core.model_library (uid, provider, model_id, context_cap_tokens, input_nanos_per_mtok, cached_input_nanos_per_mtok, output_nanos_per_mtok, created_at_ms, updated_at_ms) VALUES (
  '5b8c25b8-8703-7bcb-8af6-6dcce23342e7', 'pioneer', 'claude-fable-5', 1000000, 11000000000, 1100000000, 55000000000, 1784419200000, 1784419200000)
ON CONFLICT (provider, model_id) DO UPDATE SET
  context_cap_tokens = EXCLUDED.context_cap_tokens, input_nanos_per_mtok = EXCLUDED.input_nanos_per_mtok,
  cached_input_nanos_per_mtok = EXCLUDED.cached_input_nanos_per_mtok, output_nanos_per_mtok = EXCLUDED.output_nanos_per_mtok,
  updated_at_ms = EXCLUDED.updated_at_ms;

-- source: https://api.pioneer.ai/base-models
INSERT INTO core.model_library (uid, provider, model_id, context_cap_tokens, input_nanos_per_mtok, cached_input_nanos_per_mtok, output_nanos_per_mtok, created_at_ms, updated_at_ms) VALUES (
  'b12b093c-02c5-7aee-8d29-c9150ee5fc66', 'pioneer', 'claude-haiku-4-5', 200000, 1000000000, 100000000, 5000000000, 1784419200000, 1784419200000)
ON CONFLICT (provider, model_id) DO UPDATE SET
  context_cap_tokens = EXCLUDED.context_cap_tokens, input_nanos_per_mtok = EXCLUDED.input_nanos_per_mtok,
  cached_input_nanos_per_mtok = EXCLUDED.cached_input_nanos_per_mtok, output_nanos_per_mtok = EXCLUDED.output_nanos_per_mtok,
  updated_at_ms = EXCLUDED.updated_at_ms;

-- source: https://api.pioneer.ai/base-models
INSERT INTO core.model_library (uid, provider, model_id, context_cap_tokens, input_nanos_per_mtok, cached_input_nanos_per_mtok, output_nanos_per_mtok, created_at_ms, updated_at_ms) VALUES (
  'afad934a-82b1-7940-8c19-8767b061c9e4', 'pioneer', 'gpt-5.6-sol', 1050000, 5000000000, 500000000, 30000000000, 1784419200000, 1784419200000)
ON CONFLICT (provider, model_id) DO UPDATE SET
  context_cap_tokens = EXCLUDED.context_cap_tokens, input_nanos_per_mtok = EXCLUDED.input_nanos_per_mtok,
  cached_input_nanos_per_mtok = EXCLUDED.cached_input_nanos_per_mtok, output_nanos_per_mtok = EXCLUDED.output_nanos_per_mtok,
  updated_at_ms = EXCLUDED.updated_at_ms;

-- source: https://api.pioneer.ai/base-models
INSERT INTO core.model_library (uid, provider, model_id, context_cap_tokens, input_nanos_per_mtok, cached_input_nanos_per_mtok, output_nanos_per_mtok, created_at_ms, updated_at_ms) VALUES (
  'da28f9b8-f069-774a-8a7d-c18bb489fbd4', 'pioneer', 'gpt-5.6-terra', 1050000, 2500000000, 250000000, 15000000000, 1784419200000, 1784419200000)
ON CONFLICT (provider, model_id) DO UPDATE SET
  context_cap_tokens = EXCLUDED.context_cap_tokens, input_nanos_per_mtok = EXCLUDED.input_nanos_per_mtok,
  cached_input_nanos_per_mtok = EXCLUDED.cached_input_nanos_per_mtok, output_nanos_per_mtok = EXCLUDED.output_nanos_per_mtok,
  updated_at_ms = EXCLUDED.updated_at_ms;

-- source: https://api.pioneer.ai/base-models
INSERT INTO core.model_library (uid, provider, model_id, context_cap_tokens, input_nanos_per_mtok, cached_input_nanos_per_mtok, output_nanos_per_mtok, created_at_ms, updated_at_ms) VALUES (
  'a9c6fafa-1a5b-7575-8384-968db8e2a3e0', 'pioneer', 'gpt-5.6-luna', 1050000, 1000000000, 100000000, 6000000000, 1784419200000, 1784419200000)
ON CONFLICT (provider, model_id) DO UPDATE SET
  context_cap_tokens = EXCLUDED.context_cap_tokens, input_nanos_per_mtok = EXCLUDED.input_nanos_per_mtok,
  cached_input_nanos_per_mtok = EXCLUDED.cached_input_nanos_per_mtok, output_nanos_per_mtok = EXCLUDED.output_nanos_per_mtok,
  updated_at_ms = EXCLUDED.updated_at_ms;

-- source: https://api.pioneer.ai/base-models
INSERT INTO core.model_library (uid, provider, model_id, context_cap_tokens, input_nanos_per_mtok, cached_input_nanos_per_mtok, output_nanos_per_mtok, created_at_ms, updated_at_ms) VALUES (
  'fb8b427f-82c7-708f-8ad4-148ffa4242d1', 'pioneer', 'gpt-5.3-codex', 400000, 1750000000, 175000000, 14000000000, 1784419200000, 1784419200000)
ON CONFLICT (provider, model_id) DO UPDATE SET
  context_cap_tokens = EXCLUDED.context_cap_tokens, input_nanos_per_mtok = EXCLUDED.input_nanos_per_mtok,
  cached_input_nanos_per_mtok = EXCLUDED.cached_input_nanos_per_mtok, output_nanos_per_mtok = EXCLUDED.output_nanos_per_mtok,
  updated_at_ms = EXCLUDED.updated_at_ms;

-- source: https://api.pioneer.ai/base-models
INSERT INTO core.model_library (uid, provider, model_id, context_cap_tokens, input_nanos_per_mtok, cached_input_nanos_per_mtok, output_nanos_per_mtok, created_at_ms, updated_at_ms) VALUES (
  'b56d97f0-1779-7e56-845d-d0cb36c2466c', 'pioneer', 'gemini-3.1-pro', 1000000, 2000000000, 200000000, 12000000000, 1784419200000, 1784419200000)
ON CONFLICT (provider, model_id) DO UPDATE SET
  context_cap_tokens = EXCLUDED.context_cap_tokens, input_nanos_per_mtok = EXCLUDED.input_nanos_per_mtok,
  cached_input_nanos_per_mtok = EXCLUDED.cached_input_nanos_per_mtok, output_nanos_per_mtok = EXCLUDED.output_nanos_per_mtok,
  updated_at_ms = EXCLUDED.updated_at_ms;

-- source: https://api.pioneer.ai/base-models
INSERT INTO core.model_library (uid, provider, model_id, context_cap_tokens, input_nanos_per_mtok, cached_input_nanos_per_mtok, output_nanos_per_mtok, created_at_ms, updated_at_ms) VALUES (
  '11516a61-3f29-77b7-81fe-85a46a1e7414', 'pioneer', 'gemini-3.5-flash', 1000000, 1500000000, 150000000, 9000000000, 1784419200000, 1784419200000)
ON CONFLICT (provider, model_id) DO UPDATE SET
  context_cap_tokens = EXCLUDED.context_cap_tokens, input_nanos_per_mtok = EXCLUDED.input_nanos_per_mtok,
  cached_input_nanos_per_mtok = EXCLUDED.cached_input_nanos_per_mtok, output_nanos_per_mtok = EXCLUDED.output_nanos_per_mtok,
  updated_at_ms = EXCLUDED.updated_at_ms;

-- source: https://api.pioneer.ai/base-models
INSERT INTO core.model_library (uid, provider, model_id, context_cap_tokens, input_nanos_per_mtok, cached_input_nanos_per_mtok, output_nanos_per_mtok, created_at_ms, updated_at_ms) VALUES (
  'afa0cbdb-5150-7130-88f7-b60aff96153d', 'pioneer', 'deepseek-ai/DeepSeek-V4-Pro', 1000000, 435000000, 3625000, 870000000, 1784419200000, 1784419200000)
ON CONFLICT (provider, model_id) DO UPDATE SET
  context_cap_tokens = EXCLUDED.context_cap_tokens, input_nanos_per_mtok = EXCLUDED.input_nanos_per_mtok,
  cached_input_nanos_per_mtok = EXCLUDED.cached_input_nanos_per_mtok, output_nanos_per_mtok = EXCLUDED.output_nanos_per_mtok,
  updated_at_ms = EXCLUDED.updated_at_ms;

-- source: https://api.pioneer.ai/base-models
INSERT INTO core.model_library (uid, provider, model_id, context_cap_tokens, input_nanos_per_mtok, cached_input_nanos_per_mtok, output_nanos_per_mtok, created_at_ms, updated_at_ms) VALUES (
  '99745d30-e4d8-773f-8ffe-425b0a311d23', 'pioneer', 'deepseek-ai/DeepSeek-V4-Flash', 1000000, 140000000, 19700000, 280000000, 1784419200000, 1784419200000)
ON CONFLICT (provider, model_id) DO UPDATE SET
  context_cap_tokens = EXCLUDED.context_cap_tokens, input_nanos_per_mtok = EXCLUDED.input_nanos_per_mtok,
  cached_input_nanos_per_mtok = EXCLUDED.cached_input_nanos_per_mtok, output_nanos_per_mtok = EXCLUDED.output_nanos_per_mtok,
  updated_at_ms = EXCLUDED.updated_at_ms;

-- source: https://api.pioneer.ai/base-models
INSERT INTO core.model_library (uid, provider, model_id, context_cap_tokens, input_nanos_per_mtok, cached_input_nanos_per_mtok, output_nanos_per_mtok, created_at_ms, updated_at_ms) VALUES (
  '5ad5ad0f-c529-7c8d-8a68-ef56d180aca0', 'pioneer', 'moonshotai/Kimi-K2.7-Code', 256000, 950000000, 190000000, 4000000000, 1784419200000, 1784419200000)
ON CONFLICT (provider, model_id) DO UPDATE SET
  context_cap_tokens = EXCLUDED.context_cap_tokens, input_nanos_per_mtok = EXCLUDED.input_nanos_per_mtok,
  cached_input_nanos_per_mtok = EXCLUDED.cached_input_nanos_per_mtok, output_nanos_per_mtok = EXCLUDED.output_nanos_per_mtok,
  updated_at_ms = EXCLUDED.updated_at_ms;

-- source: https://api.pioneer.ai/base-models
INSERT INTO core.model_library (uid, provider, model_id, context_cap_tokens, input_nanos_per_mtok, cached_input_nanos_per_mtok, output_nanos_per_mtok, created_at_ms, updated_at_ms) VALUES (
  '92094fd8-39e7-7280-89b7-6214a999bb7d', 'pioneer', 'zai-org/GLM-5.2', 1000000, 1500000000, 300000000, 4500000000, 1784419200000, 1784419200000)
ON CONFLICT (provider, model_id) DO UPDATE SET
  context_cap_tokens = EXCLUDED.context_cap_tokens, input_nanos_per_mtok = EXCLUDED.input_nanos_per_mtok,
  cached_input_nanos_per_mtok = EXCLUDED.cached_input_nanos_per_mtok, output_nanos_per_mtok = EXCLUDED.output_nanos_per_mtok,
  updated_at_ms = EXCLUDED.updated_at_ms;

-- source: https://api.pioneer.ai/base-models
INSERT INTO core.model_library (uid, provider, model_id, context_cap_tokens, input_nanos_per_mtok, cached_input_nanos_per_mtok, output_nanos_per_mtok, created_at_ms, updated_at_ms) VALUES (
  '6efa7939-d1f4-7c50-8d4c-5859f0e1cf71', 'pioneer', 'MiniMaxAI/MiniMax-M3', 524288, 300000000, 60000000, 1200000000, 1784419200000, 1784419200000)
ON CONFLICT (provider, model_id) DO UPDATE SET
  context_cap_tokens = EXCLUDED.context_cap_tokens, input_nanos_per_mtok = EXCLUDED.input_nanos_per_mtok,
  cached_input_nanos_per_mtok = EXCLUDED.cached_input_nanos_per_mtok, output_nanos_per_mtok = EXCLUDED.output_nanos_per_mtok,
  updated_at_ms = EXCLUDED.updated_at_ms;

-- source: https://api.pioneer.ai/base-models
INSERT INTO core.model_library (uid, provider, model_id, context_cap_tokens, input_nanos_per_mtok, cached_input_nanos_per_mtok, output_nanos_per_mtok, created_at_ms, updated_at_ms) VALUES (
  '82cb37cf-322d-7f2b-8fe5-f35ce4b2f2bf', 'pioneer', 'grok-4.5', 500000, 2000000000, 500000000, 6000000000, 1784419200000, 1784419200000)
ON CONFLICT (provider, model_id) DO UPDATE SET
  context_cap_tokens = EXCLUDED.context_cap_tokens, input_nanos_per_mtok = EXCLUDED.input_nanos_per_mtok,
  cached_input_nanos_per_mtok = EXCLUDED.cached_input_nanos_per_mtok, output_nanos_per_mtok = EXCLUDED.output_nanos_per_mtok,
  updated_at_ms = EXCLUDED.updated_at_ms;

-- source: https://api.pioneer.ai/base-models
INSERT INTO core.model_library (uid, provider, model_id, context_cap_tokens, input_nanos_per_mtok, cached_input_nanos_per_mtok, output_nanos_per_mtok, created_at_ms, updated_at_ms) VALUES (
  '97437a05-9c64-7729-8edf-7bed46cae582', 'pioneer', 'qwen3.7-max', 991000, 1250000000, 250000000, 3750000000, 1784419200000, 1784419200000)
ON CONFLICT (provider, model_id) DO UPDATE SET
  context_cap_tokens = EXCLUDED.context_cap_tokens, input_nanos_per_mtok = EXCLUDED.input_nanos_per_mtok,
  cached_input_nanos_per_mtok = EXCLUDED.cached_input_nanos_per_mtok, output_nanos_per_mtok = EXCLUDED.output_nanos_per_mtok,
  updated_at_ms = EXCLUDED.updated_at_ms;

-- source: https://api.pioneer.ai/base-models
INSERT INTO core.model_library (uid, provider, model_id, context_cap_tokens, input_nanos_per_mtok, cached_input_nanos_per_mtok, output_nanos_per_mtok, created_at_ms, updated_at_ms) VALUES (
  'f6577c90-44da-7b76-808c-e36a3f143e51', 'pioneer', 'qwen3.7-plus', 1000000, 400000000, 80000000, 1600000000, 1784419200000, 1784419200000)
ON CONFLICT (provider, model_id) DO UPDATE SET
  context_cap_tokens = EXCLUDED.context_cap_tokens, input_nanos_per_mtok = EXCLUDED.input_nanos_per_mtok,
  cached_input_nanos_per_mtok = EXCLUDED.cached_input_nanos_per_mtok, output_nanos_per_mtok = EXCLUDED.output_nanos_per_mtok,
  updated_at_ms = EXCLUDED.updated_at_ms;

-- source: https://api.pioneer.ai/base-models
INSERT INTO core.model_library (uid, provider, model_id, context_cap_tokens, input_nanos_per_mtok, cached_input_nanos_per_mtok, output_nanos_per_mtok, created_at_ms, updated_at_ms) VALUES (
  '7e8651e1-1f52-71bf-8298-7d73596797e4', 'pioneer', 'nvidia/NVIDIA-Nemotron-3-Ultra-550B-A55B-BF16', 512288, 600000000, 150000000, 2500000000, 1784419200000, 1784419200000)
ON CONFLICT (provider, model_id) DO UPDATE SET
  context_cap_tokens = EXCLUDED.context_cap_tokens, input_nanos_per_mtok = EXCLUDED.input_nanos_per_mtok,
  cached_input_nanos_per_mtok = EXCLUDED.cached_input_nanos_per_mtok, output_nanos_per_mtok = EXCLUDED.output_nanos_per_mtok,
  updated_at_ms = EXCLUDED.updated_at_ms;

-- source: https://openrouter.ai/api/v1/models
INSERT INTO core.model_library (uid, provider, model_id, context_cap_tokens, input_nanos_per_mtok, cached_input_nanos_per_mtok, output_nanos_per_mtok, created_at_ms, updated_at_ms) VALUES (
  '85c826a5-5e42-7035-8ecd-8e593bc4912e', 'openrouter', 'anthropic/claude-opus-4.8', 1000000, 5000000000, 500000000, 25000000000, 1784419200000, 1784419200000)
ON CONFLICT (provider, model_id) DO UPDATE SET
  context_cap_tokens = EXCLUDED.context_cap_tokens, input_nanos_per_mtok = EXCLUDED.input_nanos_per_mtok,
  cached_input_nanos_per_mtok = EXCLUDED.cached_input_nanos_per_mtok, output_nanos_per_mtok = EXCLUDED.output_nanos_per_mtok,
  updated_at_ms = EXCLUDED.updated_at_ms;

-- source: https://openrouter.ai/api/v1/models
INSERT INTO core.model_library (uid, provider, model_id, context_cap_tokens, input_nanos_per_mtok, cached_input_nanos_per_mtok, output_nanos_per_mtok, created_at_ms, updated_at_ms) VALUES (
  '96bceb36-78f8-7703-8ef6-e411eed4930c', 'openrouter', 'anthropic/claude-sonnet-5', 1000000, 2000000000, 200000000, 10000000000, 1784419200000, 1784419200000)
ON CONFLICT (provider, model_id) DO UPDATE SET
  context_cap_tokens = EXCLUDED.context_cap_tokens, input_nanos_per_mtok = EXCLUDED.input_nanos_per_mtok,
  cached_input_nanos_per_mtok = EXCLUDED.cached_input_nanos_per_mtok, output_nanos_per_mtok = EXCLUDED.output_nanos_per_mtok,
  updated_at_ms = EXCLUDED.updated_at_ms;

-- source: https://openrouter.ai/api/v1/models
INSERT INTO core.model_library (uid, provider, model_id, context_cap_tokens, input_nanos_per_mtok, cached_input_nanos_per_mtok, output_nanos_per_mtok, created_at_ms, updated_at_ms) VALUES (
  'a6461809-9630-7308-83fd-a48feb5f8095', 'openrouter', 'anthropic/claude-fable-5', 1000000, 10000000000, 1000000000, 50000000000, 1784419200000, 1784419200000)
ON CONFLICT (provider, model_id) DO UPDATE SET
  context_cap_tokens = EXCLUDED.context_cap_tokens, input_nanos_per_mtok = EXCLUDED.input_nanos_per_mtok,
  cached_input_nanos_per_mtok = EXCLUDED.cached_input_nanos_per_mtok, output_nanos_per_mtok = EXCLUDED.output_nanos_per_mtok,
  updated_at_ms = EXCLUDED.updated_at_ms;

-- source: https://openrouter.ai/api/v1/models
INSERT INTO core.model_library (uid, provider, model_id, context_cap_tokens, input_nanos_per_mtok, cached_input_nanos_per_mtok, output_nanos_per_mtok, created_at_ms, updated_at_ms) VALUES (
  '7a42cf79-0a89-7906-8943-1e599db2d381', 'openrouter', 'openai/gpt-5.6-sol', 1050000, 5000000000, 500000000, 30000000000, 1784419200000, 1784419200000)
ON CONFLICT (provider, model_id) DO UPDATE SET
  context_cap_tokens = EXCLUDED.context_cap_tokens, input_nanos_per_mtok = EXCLUDED.input_nanos_per_mtok,
  cached_input_nanos_per_mtok = EXCLUDED.cached_input_nanos_per_mtok, output_nanos_per_mtok = EXCLUDED.output_nanos_per_mtok,
  updated_at_ms = EXCLUDED.updated_at_ms;

-- source: https://openrouter.ai/api/v1/models
INSERT INTO core.model_library (uid, provider, model_id, context_cap_tokens, input_nanos_per_mtok, cached_input_nanos_per_mtok, output_nanos_per_mtok, created_at_ms, updated_at_ms) VALUES (
  '97366a91-8bcf-7b78-8113-5c609f87d19f', 'openrouter', 'openai/gpt-5.6-terra', 1050000, 2500000000, 250000000, 15000000000, 1784419200000, 1784419200000)
ON CONFLICT (provider, model_id) DO UPDATE SET
  context_cap_tokens = EXCLUDED.context_cap_tokens, input_nanos_per_mtok = EXCLUDED.input_nanos_per_mtok,
  cached_input_nanos_per_mtok = EXCLUDED.cached_input_nanos_per_mtok, output_nanos_per_mtok = EXCLUDED.output_nanos_per_mtok,
  updated_at_ms = EXCLUDED.updated_at_ms;

-- source: https://openrouter.ai/api/v1/models
INSERT INTO core.model_library (uid, provider, model_id, context_cap_tokens, input_nanos_per_mtok, cached_input_nanos_per_mtok, output_nanos_per_mtok, created_at_ms, updated_at_ms) VALUES (
  'c38e80ef-77b1-7390-82d8-81a6757c3b62', 'openrouter', 'openai/gpt-5.6-luna', 1050000, 1000000000, 100000000, 6000000000, 1784419200000, 1784419200000)
ON CONFLICT (provider, model_id) DO UPDATE SET
  context_cap_tokens = EXCLUDED.context_cap_tokens, input_nanos_per_mtok = EXCLUDED.input_nanos_per_mtok,
  cached_input_nanos_per_mtok = EXCLUDED.cached_input_nanos_per_mtok, output_nanos_per_mtok = EXCLUDED.output_nanos_per_mtok,
  updated_at_ms = EXCLUDED.updated_at_ms;

-- source: https://openrouter.ai/api/v1/models
INSERT INTO core.model_library (uid, provider, model_id, context_cap_tokens, input_nanos_per_mtok, cached_input_nanos_per_mtok, output_nanos_per_mtok, created_at_ms, updated_at_ms) VALUES (
  '07cb157b-e368-7749-8a83-68802703c604', 'openrouter', 'moonshotai/kimi-k3', 1048576, 3000000000, 300000000, 15000000000, 1784419200000, 1784419200000)
ON CONFLICT (provider, model_id) DO UPDATE SET
  context_cap_tokens = EXCLUDED.context_cap_tokens, input_nanos_per_mtok = EXCLUDED.input_nanos_per_mtok,
  cached_input_nanos_per_mtok = EXCLUDED.cached_input_nanos_per_mtok, output_nanos_per_mtok = EXCLUDED.output_nanos_per_mtok,
  updated_at_ms = EXCLUDED.updated_at_ms;

-- source: https://openrouter.ai/api/v1/models
INSERT INTO core.model_library (uid, provider, model_id, context_cap_tokens, input_nanos_per_mtok, cached_input_nanos_per_mtok, output_nanos_per_mtok, created_at_ms, updated_at_ms) VALUES (
  'ae196cb3-d73f-752b-8def-646be48b196d', 'openrouter', 'moonshotai/kimi-k2.7-code', 262144, 850000000, 170000000, 3800000000, 1784419200000, 1784419200000)
ON CONFLICT (provider, model_id) DO UPDATE SET
  context_cap_tokens = EXCLUDED.context_cap_tokens, input_nanos_per_mtok = EXCLUDED.input_nanos_per_mtok,
  cached_input_nanos_per_mtok = EXCLUDED.cached_input_nanos_per_mtok, output_nanos_per_mtok = EXCLUDED.output_nanos_per_mtok,
  updated_at_ms = EXCLUDED.updated_at_ms;

-- source: https://openrouter.ai/api/v1/models
INSERT INTO core.model_library (uid, provider, model_id, context_cap_tokens, input_nanos_per_mtok, cached_input_nanos_per_mtok, output_nanos_per_mtok, created_at_ms, updated_at_ms) VALUES (
  '3367d4a6-11f7-7a66-8133-0a6ec2d43f16', 'openrouter', 'minimax/minimax-m3', 1048576, 300000000, 60000000, 1200000000, 1784419200000, 1784419200000)
ON CONFLICT (provider, model_id) DO UPDATE SET
  context_cap_tokens = EXCLUDED.context_cap_tokens, input_nanos_per_mtok = EXCLUDED.input_nanos_per_mtok,
  cached_input_nanos_per_mtok = EXCLUDED.cached_input_nanos_per_mtok, output_nanos_per_mtok = EXCLUDED.output_nanos_per_mtok,
  updated_at_ms = EXCLUDED.updated_at_ms;

-- source: https://openrouter.ai/api/v1/models
INSERT INTO core.model_library (uid, provider, model_id, context_cap_tokens, input_nanos_per_mtok, cached_input_nanos_per_mtok, output_nanos_per_mtok, created_at_ms, updated_at_ms) VALUES (
  '088a88e3-739f-7e73-825b-1054b831e23f', 'openrouter', 'x-ai/grok-4.5', 500000, 2000000000, 300000000, 6000000000, 1784419200000, 1784419200000)
ON CONFLICT (provider, model_id) DO UPDATE SET
  context_cap_tokens = EXCLUDED.context_cap_tokens, input_nanos_per_mtok = EXCLUDED.input_nanos_per_mtok,
  cached_input_nanos_per_mtok = EXCLUDED.cached_input_nanos_per_mtok, output_nanos_per_mtok = EXCLUDED.output_nanos_per_mtok,
  updated_at_ms = EXCLUDED.updated_at_ms;

-- source: https://openrouter.ai/api/v1/models
INSERT INTO core.model_library (uid, provider, model_id, context_cap_tokens, input_nanos_per_mtok, cached_input_nanos_per_mtok, output_nanos_per_mtok, created_at_ms, updated_at_ms) VALUES (
  '2a7282a3-e338-7f08-8c2a-393b9f97fa5f', 'openrouter', 'qwen/qwen3.7-max', 1000000, 1475000000, 295000000, 4425000000, 1784419200000, 1784419200000)
ON CONFLICT (provider, model_id) DO UPDATE SET
  context_cap_tokens = EXCLUDED.context_cap_tokens, input_nanos_per_mtok = EXCLUDED.input_nanos_per_mtok,
  cached_input_nanos_per_mtok = EXCLUDED.cached_input_nanos_per_mtok, output_nanos_per_mtok = EXCLUDED.output_nanos_per_mtok,
  updated_at_ms = EXCLUDED.updated_at_ms;

-- source: https://docs.fireworks.ai/serverless/pricing
INSERT INTO core.model_library (uid, provider, model_id, context_cap_tokens, input_nanos_per_mtok, cached_input_nanos_per_mtok, output_nanos_per_mtok, created_at_ms, updated_at_ms) VALUES (
  'd5fdf612-4b3d-7a22-80c8-3b70a4797fd9', 'fireworks', 'accounts/fireworks/models/deepseek-v4-pro', 1048576, 1740000000, 145000000, 3480000000, 1784419200000, 1784419200000)
ON CONFLICT (provider, model_id) DO UPDATE SET
  context_cap_tokens = EXCLUDED.context_cap_tokens, input_nanos_per_mtok = EXCLUDED.input_nanos_per_mtok,
  cached_input_nanos_per_mtok = EXCLUDED.cached_input_nanos_per_mtok, output_nanos_per_mtok = EXCLUDED.output_nanos_per_mtok,
  updated_at_ms = EXCLUDED.updated_at_ms;

-- source: https://docs.fireworks.ai/serverless/pricing
INSERT INTO core.model_library (uid, provider, model_id, context_cap_tokens, input_nanos_per_mtok, cached_input_nanos_per_mtok, output_nanos_per_mtok, created_at_ms, updated_at_ms) VALUES (
  '549fe147-6d9e-7b80-8c05-cae68677c673', 'fireworks', 'accounts/fireworks/models/deepseek-v4-flash', 1048576, 140000000, 28000000, 280000000, 1784419200000, 1784419200000)
ON CONFLICT (provider, model_id) DO UPDATE SET
  context_cap_tokens = EXCLUDED.context_cap_tokens, input_nanos_per_mtok = EXCLUDED.input_nanos_per_mtok,
  cached_input_nanos_per_mtok = EXCLUDED.cached_input_nanos_per_mtok, output_nanos_per_mtok = EXCLUDED.output_nanos_per_mtok,
  updated_at_ms = EXCLUDED.updated_at_ms;

-- source: https://docs.fireworks.ai/serverless/pricing
INSERT INTO core.model_library (uid, provider, model_id, context_cap_tokens, input_nanos_per_mtok, cached_input_nanos_per_mtok, output_nanos_per_mtok, created_at_ms, updated_at_ms) VALUES (
  '7a65c226-0ddb-7fee-8770-a6107b4b27df', 'fireworks', 'accounts/fireworks/models/kimi-k2p7-code', 262144, 950000000, 190000000, 4000000000, 1784419200000, 1784419200000)
ON CONFLICT (provider, model_id) DO UPDATE SET
  context_cap_tokens = EXCLUDED.context_cap_tokens, input_nanos_per_mtok = EXCLUDED.input_nanos_per_mtok,
  cached_input_nanos_per_mtok = EXCLUDED.cached_input_nanos_per_mtok, output_nanos_per_mtok = EXCLUDED.output_nanos_per_mtok,
  updated_at_ms = EXCLUDED.updated_at_ms;

-- source: https://docs.fireworks.ai/serverless/pricing
INSERT INTO core.model_library (uid, provider, model_id, context_cap_tokens, input_nanos_per_mtok, cached_input_nanos_per_mtok, output_nanos_per_mtok, created_at_ms, updated_at_ms) VALUES (
  '9b40be0f-5993-7195-8234-cffa7aa0ef3f', 'fireworks', 'accounts/fireworks/models/glm-5p2', 1048576, 1400000000, 140000000, 4400000000, 1784419200000, 1784419200000)
ON CONFLICT (provider, model_id) DO UPDATE SET
  context_cap_tokens = EXCLUDED.context_cap_tokens, input_nanos_per_mtok = EXCLUDED.input_nanos_per_mtok,
  cached_input_nanos_per_mtok = EXCLUDED.cached_input_nanos_per_mtok, output_nanos_per_mtok = EXCLUDED.output_nanos_per_mtok,
  updated_at_ms = EXCLUDED.updated_at_ms;

-- source: https://docs.fireworks.ai/serverless/pricing
INSERT INTO core.model_library (uid, provider, model_id, context_cap_tokens, input_nanos_per_mtok, cached_input_nanos_per_mtok, output_nanos_per_mtok, created_at_ms, updated_at_ms) VALUES (
  'cff96d38-9b84-7668-888d-97efe6c36fc8', 'fireworks', 'accounts/fireworks/models/qwen3p7-plus', 262144, 400000000, 80000000, 1600000000, 1784419200000, 1784419200000)
ON CONFLICT (provider, model_id) DO UPDATE SET
  context_cap_tokens = EXCLUDED.context_cap_tokens, input_nanos_per_mtok = EXCLUDED.input_nanos_per_mtok,
  cached_input_nanos_per_mtok = EXCLUDED.cached_input_nanos_per_mtok, output_nanos_per_mtok = EXCLUDED.output_nanos_per_mtok,
  updated_at_ms = EXCLUDED.updated_at_ms;

-- source: https://docs.fireworks.ai/serverless/pricing
INSERT INTO core.model_library (uid, provider, model_id, context_cap_tokens, input_nanos_per_mtok, cached_input_nanos_per_mtok, output_nanos_per_mtok, created_at_ms, updated_at_ms) VALUES (
  'fc82f965-20bb-78a5-8b37-b7afd915bf4b', 'fireworks', 'accounts/fireworks/models/minimax-m3', 512000, 300000000, 60000000, 1200000000, 1784419200000, 1784419200000)
ON CONFLICT (provider, model_id) DO UPDATE SET
  context_cap_tokens = EXCLUDED.context_cap_tokens, input_nanos_per_mtok = EXCLUDED.input_nanos_per_mtok,
  cached_input_nanos_per_mtok = EXCLUDED.cached_input_nanos_per_mtok, output_nanos_per_mtok = EXCLUDED.output_nanos_per_mtok,
  updated_at_ms = EXCLUDED.updated_at_ms;

-- source: https://docs.fireworks.ai/serverless/pricing
INSERT INTO core.model_library (uid, provider, model_id, context_cap_tokens, input_nanos_per_mtok, cached_input_nanos_per_mtok, output_nanos_per_mtok, created_at_ms, updated_at_ms) VALUES (
  '5dda07af-b6cc-746d-859f-fa652635d869', 'fireworks', 'accounts/fireworks/models/gpt-oss-120b', 131072, 150000000, 15000000, 600000000, 1784419200000, 1784419200000)
ON CONFLICT (provider, model_id) DO UPDATE SET
  context_cap_tokens = EXCLUDED.context_cap_tokens, input_nanos_per_mtok = EXCLUDED.input_nanos_per_mtok,
  cached_input_nanos_per_mtok = EXCLUDED.cached_input_nanos_per_mtok, output_nanos_per_mtok = EXCLUDED.output_nanos_per_mtok,
  updated_at_ms = EXCLUDED.updated_at_ms;

-- source: https://docs.together.ai/docs/serverless-models
INSERT INTO core.model_library (uid, provider, model_id, context_cap_tokens, input_nanos_per_mtok, cached_input_nanos_per_mtok, output_nanos_per_mtok, created_at_ms, updated_at_ms) VALUES (
  'ffb873fd-6ea6-7a1b-8270-50df42d6af6b', 'together-ai', 'deepseek-ai/DeepSeek-V4-Pro', 512000, 1740000000, 200000000, 3480000000, 1784419200000, 1784419200000)
ON CONFLICT (provider, model_id) DO UPDATE SET
  context_cap_tokens = EXCLUDED.context_cap_tokens, input_nanos_per_mtok = EXCLUDED.input_nanos_per_mtok,
  cached_input_nanos_per_mtok = EXCLUDED.cached_input_nanos_per_mtok, output_nanos_per_mtok = EXCLUDED.output_nanos_per_mtok,
  updated_at_ms = EXCLUDED.updated_at_ms;

-- source: https://docs.together.ai/docs/serverless-models
INSERT INTO core.model_library (uid, provider, model_id, context_cap_tokens, input_nanos_per_mtok, cached_input_nanos_per_mtok, output_nanos_per_mtok, created_at_ms, updated_at_ms) VALUES (
  '3a51abc7-63f8-7796-8174-851ccab19f70', 'together-ai', 'moonshotai/Kimi-K2.7-Code', 262144, 950000000, 190000000, 4000000000, 1784419200000, 1784419200000)
ON CONFLICT (provider, model_id) DO UPDATE SET
  context_cap_tokens = EXCLUDED.context_cap_tokens, input_nanos_per_mtok = EXCLUDED.input_nanos_per_mtok,
  cached_input_nanos_per_mtok = EXCLUDED.cached_input_nanos_per_mtok, output_nanos_per_mtok = EXCLUDED.output_nanos_per_mtok,
  updated_at_ms = EXCLUDED.updated_at_ms;

-- source: https://docs.together.ai/docs/serverless-models
INSERT INTO core.model_library (uid, provider, model_id, context_cap_tokens, input_nanos_per_mtok, cached_input_nanos_per_mtok, output_nanos_per_mtok, created_at_ms, updated_at_ms) VALUES (
  '85445b35-23ec-713b-864f-00a8a990ac1e', 'together-ai', 'zai-org/GLM-5.2', 262144, 1400000000, 260000000, 4400000000, 1784419200000, 1784419200000)
ON CONFLICT (provider, model_id) DO UPDATE SET
  context_cap_tokens = EXCLUDED.context_cap_tokens, input_nanos_per_mtok = EXCLUDED.input_nanos_per_mtok,
  cached_input_nanos_per_mtok = EXCLUDED.cached_input_nanos_per_mtok, output_nanos_per_mtok = EXCLUDED.output_nanos_per_mtok,
  updated_at_ms = EXCLUDED.updated_at_ms;

-- source: https://docs.together.ai/docs/serverless-models
INSERT INTO core.model_library (uid, provider, model_id, context_cap_tokens, input_nanos_per_mtok, cached_input_nanos_per_mtok, output_nanos_per_mtok, created_at_ms, updated_at_ms) VALUES (
  '2f9b2edf-a06c-793d-84c3-74047a4bf598', 'together-ai', 'MiniMaxAI/MiniMax-M3', 524288, 300000000, 60000000, 1200000000, 1784419200000, 1784419200000)
ON CONFLICT (provider, model_id) DO UPDATE SET
  context_cap_tokens = EXCLUDED.context_cap_tokens, input_nanos_per_mtok = EXCLUDED.input_nanos_per_mtok,
  cached_input_nanos_per_mtok = EXCLUDED.cached_input_nanos_per_mtok, output_nanos_per_mtok = EXCLUDED.output_nanos_per_mtok,
  updated_at_ms = EXCLUDED.updated_at_ms;

-- source: https://docs.together.ai/docs/serverless-models
INSERT INTO core.model_library (uid, provider, model_id, context_cap_tokens, input_nanos_per_mtok, cached_input_nanos_per_mtok, output_nanos_per_mtok, created_at_ms, updated_at_ms) VALUES (
  'b5a7ae30-dd71-7da3-8e5a-58de6e05652b', 'together-ai', 'Qwen/Qwen3.7-Plus', 1000000, 320000000, 320000000, 1280000000, 1784419200000, 1784419200000)
ON CONFLICT (provider, model_id) DO UPDATE SET
  context_cap_tokens = EXCLUDED.context_cap_tokens, input_nanos_per_mtok = EXCLUDED.input_nanos_per_mtok,
  cached_input_nanos_per_mtok = EXCLUDED.cached_input_nanos_per_mtok, output_nanos_per_mtok = EXCLUDED.output_nanos_per_mtok,
  updated_at_ms = EXCLUDED.updated_at_ms;

-- source: https://novita.ai/pricing
INSERT INTO core.model_library (uid, provider, model_id, context_cap_tokens, input_nanos_per_mtok, cached_input_nanos_per_mtok, output_nanos_per_mtok, created_at_ms, updated_at_ms) VALUES (
  'd6fa6836-33cd-75b0-8fe2-de9477600ae3', 'novita', 'moonshotai/kimi-k3', 1048576, 3000000000, 300000000, 15000000000, 1784419200000, 1784419200000)
ON CONFLICT (provider, model_id) DO UPDATE SET
  context_cap_tokens = EXCLUDED.context_cap_tokens, input_nanos_per_mtok = EXCLUDED.input_nanos_per_mtok,
  cached_input_nanos_per_mtok = EXCLUDED.cached_input_nanos_per_mtok, output_nanos_per_mtok = EXCLUDED.output_nanos_per_mtok,
  updated_at_ms = EXCLUDED.updated_at_ms;

-- source: https://novita.ai/pricing
INSERT INTO core.model_library (uid, provider, model_id, context_cap_tokens, input_nanos_per_mtok, cached_input_nanos_per_mtok, output_nanos_per_mtok, created_at_ms, updated_at_ms) VALUES (
  '3b1299ec-2643-79aa-83b7-db12402bd98a', 'novita', 'moonshotai/kimi-k2.7-code', 262144, 950000000, 190000000, 4000000000, 1784419200000, 1784419200000)
ON CONFLICT (provider, model_id) DO UPDATE SET
  context_cap_tokens = EXCLUDED.context_cap_tokens, input_nanos_per_mtok = EXCLUDED.input_nanos_per_mtok,
  cached_input_nanos_per_mtok = EXCLUDED.cached_input_nanos_per_mtok, output_nanos_per_mtok = EXCLUDED.output_nanos_per_mtok,
  updated_at_ms = EXCLUDED.updated_at_ms;

-- source: https://novita.ai/pricing
INSERT INTO core.model_library (uid, provider, model_id, context_cap_tokens, input_nanos_per_mtok, cached_input_nanos_per_mtok, output_nanos_per_mtok, created_at_ms, updated_at_ms) VALUES (
  '5701049e-dd76-7d42-85f5-fd2defa63b8d', 'novita', 'deepseek/deepseek-v4-pro', 1048576, 1600000000, 135000000, 3200000000, 1784419200000, 1784419200000)
ON CONFLICT (provider, model_id) DO UPDATE SET
  context_cap_tokens = EXCLUDED.context_cap_tokens, input_nanos_per_mtok = EXCLUDED.input_nanos_per_mtok,
  cached_input_nanos_per_mtok = EXCLUDED.cached_input_nanos_per_mtok, output_nanos_per_mtok = EXCLUDED.output_nanos_per_mtok,
  updated_at_ms = EXCLUDED.updated_at_ms;

-- source: https://novita.ai/pricing
INSERT INTO core.model_library (uid, provider, model_id, context_cap_tokens, input_nanos_per_mtok, cached_input_nanos_per_mtok, output_nanos_per_mtok, created_at_ms, updated_at_ms) VALUES (
  '31bb49d9-f242-708a-874c-c60c30f4c484', 'novita', 'deepseek/deepseek-v4-flash', 1048576, 140000000, 28000000, 280000000, 1784419200000, 1784419200000)
ON CONFLICT (provider, model_id) DO UPDATE SET
  context_cap_tokens = EXCLUDED.context_cap_tokens, input_nanos_per_mtok = EXCLUDED.input_nanos_per_mtok,
  cached_input_nanos_per_mtok = EXCLUDED.cached_input_nanos_per_mtok, output_nanos_per_mtok = EXCLUDED.output_nanos_per_mtok,
  updated_at_ms = EXCLUDED.updated_at_ms;

-- source: https://novita.ai/pricing
INSERT INTO core.model_library (uid, provider, model_id, context_cap_tokens, input_nanos_per_mtok, cached_input_nanos_per_mtok, output_nanos_per_mtok, created_at_ms, updated_at_ms) VALUES (
  '944c42aa-2001-7db2-8ddb-815b069d24ed', 'novita', 'zai-org/glm-5.2', 1048576, 1400000000, 260000000, 4400000000, 1784419200000, 1784419200000)
ON CONFLICT (provider, model_id) DO UPDATE SET
  context_cap_tokens = EXCLUDED.context_cap_tokens, input_nanos_per_mtok = EXCLUDED.input_nanos_per_mtok,
  cached_input_nanos_per_mtok = EXCLUDED.cached_input_nanos_per_mtok, output_nanos_per_mtok = EXCLUDED.output_nanos_per_mtok,
  updated_at_ms = EXCLUDED.updated_at_ms;

-- source: https://novita.ai/pricing
INSERT INTO core.model_library (uid, provider, model_id, context_cap_tokens, input_nanos_per_mtok, cached_input_nanos_per_mtok, output_nanos_per_mtok, created_at_ms, updated_at_ms) VALUES (
  '5183cec3-3313-77a3-8306-f2fb3adfd301', 'novita', 'qwen/qwen3.7-max', 1000000, 1250000000, 250000000, 3750000000, 1784419200000, 1784419200000)
ON CONFLICT (provider, model_id) DO UPDATE SET
  context_cap_tokens = EXCLUDED.context_cap_tokens, input_nanos_per_mtok = EXCLUDED.input_nanos_per_mtok,
  cached_input_nanos_per_mtok = EXCLUDED.cached_input_nanos_per_mtok, output_nanos_per_mtok = EXCLUDED.output_nanos_per_mtok,
  updated_at_ms = EXCLUDED.updated_at_ms;

