//! The one error type returned by operator read projections.

use afd_core::error_code::{self, ErrorCode};

/// Result returned by every fallible operator projection.
///
/// Written here rather than generated by [`afd_core::error_shell!`] because an
/// alias a reader cannot see does not serve the rule it exists for
/// (`RUST_ERROR_STANDARD` rule 1).
pub type Result<T, E = Error> = core::result::Result<T, E>;

afd_core::error_shell!(
    /// A fleet operator projection failed.
    pub struct Error(ErrorKind);
);

#[derive(Debug, thiserror::Error)]
enum ErrorKind {
    #[error("the datastore backing operator views would not answer")]
    Datastore {
        #[source]
        source: afd_db::Error,
    },
    #[error("statement failed during {context}")]
    Query {
        context: &'static str,
        #[source]
        source: sqlx::Error,
    },
    #[error("a runner lease row holds an unreadable {column}")]
    Row {
        column: &'static str,
        #[source]
        source: sqlx::Error,
    },
    #[error("no runner matches the operator-supplied id")]
    RunnerNotFound,
    #[error("the lease cursor is outside the filtered runner history")]
    CursorInvalid,
}

impl Error {
    #[must_use]
    /// Registry code exposed to the API shell.
    pub const fn code(&self) -> ErrorCode {
        match *self.kind() {
            ErrorKind::Datastore { .. } => error_code::INTERNAL_DB_UNAVAILABLE,
            ErrorKind::Query { .. } | ErrorKind::Row { .. } => error_code::INTERNAL_DB_QUERY,
            ErrorKind::RunnerNotFound => error_code::RUNNER_NOT_FOUND,
            ErrorKind::CursorInvalid => error_code::INVALID_REQUEST,
        }
    }

    #[must_use]
    /// Client-safe detail exposed to the API shell.
    pub const fn detail(&self) -> &'static str {
        match *self.kind() {
            ErrorKind::Datastore { .. } => "Database unavailable",
            ErrorKind::Query { .. } | ErrorKind::Row { .. } => "Database error",
            ErrorKind::RunnerNotFound => "Runner not found",
            ErrorKind::CursorInvalid => super::runner_leases::DETAIL_BAD_CURSOR,
        }
    }

    #[must_use]
    /// Whether the backing datastore could not be reached at all.
    pub const fn is_datastore_unavailable(&self) -> bool {
        matches!(*self.kind(), ErrorKind::Datastore { .. })
    }
}

afd_core::error_lifts!(Error, ErrorKind: afd_db::Error => Datastore);

pub(super) fn query(context: &'static str) -> impl Fn(sqlx::Error) -> Error {
    move |source| Error::from(ErrorKind::Query { context, source })
}

pub(super) fn row(column: &'static str) -> impl Fn(sqlx::Error) -> Error {
    move |source| Error::from(ErrorKind::Row { column, source })
}

pub(super) fn runner_not_found() -> Error {
    Error::from(ErrorKind::RunnerNotFound)
}

pub(super) fn cursor_invalid() -> Error {
    Error::from(ErrorKind::CursorInvalid)
}

#[cfg(test)]
#[path = "error/tests.rs"]
mod tests;
