//! The one error type returned by platform administration repositories.

use afd_core::error_code::{self, ErrorCode};

/// Result returned by every fallible administration operation.
///
/// Written here rather than generated by [`afd_core::error_shell!`] because an
/// alias a reader cannot see does not serve the rule it exists for
/// (`RUST_ERROR_STANDARD` rule 1).
pub type Result<T, E = Error> = core::result::Result<T, E>;

afd_core::error_shell!(
    /// A platform administration operation failed.
    pub struct Error(ErrorKind);
);

#[derive(Debug, thiserror::Error)]
enum ErrorKind {
    #[error("the datastore backing platform administration would not answer")]
    Datastore {
        #[source]
        source: afd_db::Error,
    },
    #[error("statement failed during {context}")]
    Query {
        context: &'static str,
        #[source]
        source: sqlx::Error,
    },
    #[error("a {table} row holds an unreadable {column}")]
    Row {
        table: &'static str,
        column: &'static str,
        #[source]
        source: afd_core::error::Error,
    },
    #[error("could not draw entropy for a model identifier")]
    Entropy {
        #[source]
        source: afd_crypto::error::Error,
    },
    #[error("a model identifier could not represent the current instant")]
    Mint {
        #[source]
        source: afd_core::error::Error,
    },
}

impl Error {
    /// Registry code exposed to the API shell.
    #[must_use]
    pub const fn code(&self) -> ErrorCode {
        match *self.kind() {
            ErrorKind::Datastore { .. } => error_code::INTERNAL_DB_UNAVAILABLE,
            ErrorKind::Query { .. } | ErrorKind::Row { .. } => error_code::INTERNAL_DB_QUERY,
            ErrorKind::Entropy { .. } | ErrorKind::Mint { .. } => {
                error_code::INTERNAL_OPERATION_FAILED
            }
        }
    }

    /// Client-safe detail exposed to the API shell.
    #[must_use]
    pub const fn detail(&self) -> &'static str {
        match *self.kind() {
            ErrorKind::Datastore { .. } => "Database unavailable",
            ErrorKind::Query { .. } | ErrorKind::Row { .. } => "Database error",
            ErrorKind::Entropy { .. } | ErrorKind::Mint { .. } => "Internal operation failed",
        }
    }

    /// Whether the backing datastore could not be reached at all.
    #[must_use]
    pub const fn is_datastore_unavailable(&self) -> bool {
        matches!(*self.kind(), ErrorKind::Datastore { .. })
    }
}

afd_core::error_lifts!(Error, ErrorKind:
    afd_db::Error => Datastore,
    afd_crypto::error::Error => Entropy,
    afd_core::error::Error => Mint,
);

pub(super) fn query(context: &'static str) -> impl Fn(sqlx::Error) -> Error {
    move |source| Error::from(ErrorKind::Query { context, source })
}

pub(super) fn row(
    table: &'static str,
    column: &'static str,
) -> impl Fn(afd_core::error::Error) -> Error {
    move |source| {
        Error::from(ErrorKind::Row {
            table,
            column,
            source,
        })
    }
}

#[cfg(test)]
#[path = "error/tests.rs"]
mod tests;
