//! The one error type this crate returns, and the wire code each failure maps to.
//!
//! Same shape as [`afd_db::Error`] (`M-ERRORS-CANONICAL-STRUCTS`): a struct
//! carrying a captured backtrace and a private kind, with `is_*` accessors
//! rather than a public enum, so a new internal failure mode is not a breaking
//! change for anyone matching on it.
//!
//! # Why a type rather than a log line
//!
//! A lease path that answers `Option<T>` and logs on the way past cannot tell
//! a transient Postgres blip from an idle fleet: both reach the caller as the
//! same value, and the only thing that knows the difference is a log line
//! nobody reads at request time.
//!
//! That is RULE ECL's failure exactly, and it is not fixed by adding a log. It
//! is fixed by making the difference a TYPE the caller has to handle, which is
//! what this file is for. The lease verb still answers no-work-with-backoff on
//! a transient failure, but it does so at ONE place that says so, instead of
//! at every catch site deciding it privately.

pub mod classify;
pub mod detail;
pub mod lift;
pub mod permanence;
pub mod refuse;
pub mod report;

#[cfg(test)]
mod lift_tests;
#[cfg(test)]
mod tests;

pub use self::detail::{
    DETAIL_BUDGET_EXHAUSTED, DETAIL_BUNDLE_FETCH_FAILED, DETAIL_BUNDLE_NOT_FOUND,
    DETAIL_BUNDLE_STORAGE_UNAVAILABLE, DETAIL_CONFIG_UNREADABLE, DETAIL_CREDENTIAL_MISSING,
    DETAIL_DATABASE_ERROR, DETAIL_DATABASE_UNAVAILABLE, DETAIL_EVENT_MALFORMED,
    DETAIL_GATE_BINDING_UNWRITABLE, DETAIL_GATE_REFERENCE_UNWRITABLE, DETAIL_HOST_ID_BOUNDS,
    DETAIL_LEASE_LOST, DETAIL_LEASE_MAX_RUNTIME, DETAIL_LEASE_NOT_FOUND, DETAIL_MESSAGE_LIMIT,
    DETAIL_MESSAGE_NO_CHANNEL, DETAIL_PROVIDER_UNRESOLVED, DETAIL_QUEUE_UNAVAILABLE,
    DETAIL_REGISTRATION_FAILED, DETAIL_REGISTRY_ALLOWLIST, DETAIL_RENEWAL_NO_CREDITS,
    DETAIL_RUNNER_NOT_FOUND, DETAIL_STALE_FENCE, DETAIL_VAULT_DATA_INVALID,
};
// The mint family's sentences, listed apart from the block above because they
// are read together: every one is a refusal the credential mint path answers.
pub use self::detail::{
    DETAIL_CONNECTOR_MINT_FAILED, DETAIL_CONNECTOR_RECONNECT, DETAIL_GITHUB_RECONNECT,
    DETAIL_GRANT_REQUIRED, DETAIL_INTEGRATION_NOT_CONNECTED, DETAIL_MINT_FAILED,
    DETAIL_MINT_UNCONFIGURED,
};
/// Everything that REFUSES a request, re-exported as one group so no call site
/// names the file the cap moved them into.
pub(crate) use self::refuse::{
    budget_exhausted, connector_mint_failed, connector_reconnect_required, github_mint_failed,
    github_reconnect_required, grant_required, integration_not_connected, lease_lost,
    lease_max_runtime, lease_not_found, message_limit_reached, message_no_channel,
    mint_unconfigured, renewal_no_credits, stale_fence,
};
/// Everything that REPORTS a failure rather than answering one, re-exported so
/// no call site names the file the cap moved them into.
pub(crate) use self::report::{
    bundle_missing, bundle_oversized, bundle_storage, bundle_unconfigured, envelope_field,
    envelope_malformed, query, rejected, row_malformed, sequence_corrupt, vault_data_invalid,
};

/// The result every fallible function in this crate returns.
///
/// One alias per crate, defaulted to this crate's own [`Error`], so a reader
/// never has to check WHICH error a signature returns to know it is this one
/// (`RUST_ERROR_STANDARD` rule 1). Written here rather than generated by
/// [`afd_core::error_shell!`] because an alias a reader cannot see does not
/// serve the rule it exists for.
pub type Result<T, E = Error> = core::result::Result<T, E>;

afd_core::error_shell!(
    /// A runner-plane failure, with the backtrace of where it was raised.
    ///
    /// One pointer wide, for the reason `afd_db::Error` is: the largest kind
    /// carries a `sqlx::Error` at 128 bytes, and this type is the `Err` of
    /// `Result`s the request path returns. Boxing keeps the success path — the
    /// one that runs — the size of what it actually carries
    /// (`clippy::result_large_err`).
    pub struct Error(ErrorKind);
);

/// What actually went wrong. Private so a new variant is not a breaking change.
#[derive(Debug, thiserror::Error)]
pub(crate) enum ErrorKind {
    #[error("the datastore backing the runner plane would not answer")]
    Datastore {
        #[source]
        source: afd_db::Error,
    },

    #[error("the gate plane could not answer for the runner plane")]
    Gate {
        #[source]
        source: afd_gate::Error,
    },

    #[error("the credential plane could not answer for the runner plane")]
    Credential {
        #[source]
        source: afd_credential::Error,
    },

    #[error("the queue backing the runner plane would not answer")]
    Queue {
        #[source]
        source: afd_dragonfly::Error,
    },

    /// The admission ledger could not say where a lost consumer group
    /// should resume.
    #[error("the admission ledger could not answer for the runner plane")]
    Admission {
        #[source]
        source: afd_admission::Error,
    },

    #[error("the billing store could not answer for the runner plane")]
    Billing {
        #[source]
        source: afd_billing::Error,
    },

    #[error("statement failed during {context}")]
    Query {
        context: &'static str,
        #[source]
        source: sqlx::Error,
    },

    #[error("a {table} row holds a value this daemon cannot read: {column}")]
    RowMalformed {
        table: &'static str,
        column: &'static str,
        #[source]
        source: afd_core::error::Error,
    },

    #[error("the event store could not answer for the runner plane")]
    Events {
        #[source]
        source: afd_events::Error,
    },

    /// The delivery ledger would not answer.
    ///
    /// `afd_outbound` owns `core.fleet_obligations`, and the report path commits
    /// an obligation through it inside its own transaction — so a failure there
    /// is a failure of THIS transaction and has to reach the caller as one.
    /// Distinct from [`Self::Datastore`] because the obligation is a PostgreSQL
    /// row, not a queue entry, and the two fail for different reasons.
    #[error("the delivery ledger could not answer for the runner plane")]
    Outbound {
        #[source]
        source: afd_outbound::Error,
    },

    #[error("the leased event envelope is missing {field}")]
    Envelope { field: &'static str },

    #[error("the leased event envelope's {field} is present but unreadable")]
    EnvelopeMalformed { field: &'static str },

    #[error("{detail}")]
    Rejected { detail: &'static str },

    #[error("an identifier could not be minted from the current instant")]
    Mint {
        #[from]
        source: afd_core::error::Error,
    },

    #[error("could not draw the entropy a credential is minted from")]
    Entropy {
        #[source]
        source: afd_crypto::error::Error,
    },

    #[error("the fleet's stored configuration cannot be read")]
    ConfigUnreadable {
        #[from]
        source: afd_fleet_runtime::Error,
    },

    #[error("a stored credential body is not the JSON object the tool bridge addresses")]
    VaultDataInvalid,

    #[error("a stored fencing sequence is not a sequence")]
    SequenceCorrupt,

    #[error("the reporting holder's fence is behind the fleet's live sequence")]
    StaleFence,

    #[error("no lease with that id belongs to the presenting runner")]
    LeaseNotFound,

    #[error("the lease is no longer this runner's to renew")]
    LeaseLost,

    #[error("the lease reached the hard ceiling on one run's wall time")]
    LeaseMaxRuntime,

    #[error("the tenant's credit pool cannot fund another slice of this run")]
    RenewalNoCredits,

    #[error("the fleet reached a spend ceiling its own author declared")]
    BudgetExhausted,

    #[error("the leased event recorded no thread a message can go to")]
    MessageNoChannel,

    #[error("the lease already posted as many messages as one run may")]
    MessageLimitReached,

    #[error("the fleet's secret values could not be gathered into a mask")]
    Scrub {
        #[source]
        source: afr_secrets::Error,
    },

    #[error("no Fleet Bundle snapshot is stored under that content hash")]
    BundleMissing,

    #[error("this deployment has no Fleet Bundle snapshot storage configured")]
    BundleUnconfigured,

    #[error("the Fleet Bundle snapshot store would not answer")]
    BundleStorage {
        #[source]
        source: object_store::Error,
    },

    #[error("a stored Fleet Bundle snapshot is larger than this daemon buffers: {size} bytes")]
    BundleOversized { size: u64 },

    #[error("this workspace has connected no integration under that name")]
    IntegrationNotConnected,

    #[error("this deployment holds no platform credential for that connector")]
    MintUnconfigured,

    #[error("the GitHub App installation this handle names is gone")]
    GithubReconnectRequired,

    #[error("GitHub returned no installation token this daemon would hand over")]
    GithubMintFailed,

    #[error("the connector's stored authorization is no longer redeemable")]
    ConnectorReconnectRequired,

    #[error("the connector's token exchange produced no credential")]
    ConnectorMintFailed,

    #[error("the fleet holds no approved grant for that integration")]
    GrantRequired,

    #[error("the fleet's memory could not be read or written")]
    Memory {
        #[source]
        source: afd_memory::Error,
    },
}

/// The refusals a suite outside this crate needs to CONSTRUCT.
///
/// M-TEST-UTIL. The router suites stub the lease plane, and a stub for the mint
/// verb has no honest success to answer with — it holds no vault row, no grant
/// and no vendor — so it answers the refusal a deployment with no platform
/// credentials gives. Every other constructor stays `pub(crate)`: this is a
/// seam for a stub, not a way for another crate to invent this plane's
/// refusals.
#[cfg(feature = "test-util")]
impl Error {
    /// The refusal a deployment holding no platform credential answers.
    #[must_use]
    pub fn mint_unconfigured() -> Self {
        super::error::mint_unconfigured()
    }

    /// The refusal a lease this runner does not hold answers: what a stub
    /// plane with no lease rows says to every lease-addressed verb.
    #[must_use]
    pub fn lease_not_found() -> Self {
        super::error::lease_not_found()
    }

    /// The refusal an uninstalled or revoked GitHub App answers a mint with:
    /// the one mint refusal a route renders as a conflict naming its state.
    #[must_use]
    pub fn github_reconnect_required() -> Self {
        super::error::github_reconnect_required()
    }

    /// The refusal a fenced verb answers a superseded lease, or a token not
    /// the lease's own, with: the memory routes render it as a conflict.
    #[must_use]
    pub fn stale_fence() -> Self {
        super::error::stale_fence()
    }
}

impl Error {
    /// Raises `kind` as an error, capturing a backtrace.
    ///
    /// A thin pass through the generated `From<ErrorKind>` — kept because the
    /// raise sites in this crate spell `Error::new(...)`.
    pub(crate) fn new(kind: ErrorKind) -> Self {
        Self::from(kind)
    }
}
