//! The one error type this crate returns, and what each failure tells a caller.
//!
//! Same shape as [`afd_db::Error`] and `afd_tenant::Error`
//! (`M-ERRORS-CANONICAL-STRUCTS`, with the workspace's declared divergence): a
//! struct carrying a captured backtrace and a private kind, with `is_*`
//! accessors rather than a public enum, so a new failure mode is not a breaking
//! change for anybody matching on it.
//!
//! # One table, not two
//!
//! [`Error::answer`] returns the registry code AND the sentence together, and
//! both public accessors read from it. The Zig handlers spell
//! `hx.fail(code, detail)` at each call site with nothing relating the two, so
//! two handlers can describe one failure differently and both compile. Here a
//! kind cannot take its code and its sentence from different places.
//!
//! # Where a failure is raised
//!
//! A variant carrying no data needs no constructor — `ErrorKind::NotFound.into()`
//! names what a `fn not_found()` would. The kinds that CARRY something keep a
//! raiser, and those live in [`raise`] beside the `From` impls that lift a
//! foreign error into its variant.

use afd_core::error_code::{self, ErrorCode};

pub mod detail;
mod raise;

pub(crate) use self::raise::{query, row_malformed, skill, source_stale};

/// The result every fallible function in this crate returns.
///
/// One alias per crate, defaulted to this crate's own [`Error`], so a reader
/// never has to check WHICH error a signature returns to know it is this one
/// (`RUST_ERROR_STANDARD` rule 1). Written here rather than generated by
/// [`afd_core::error_shell!`] because an alias a reader cannot see does not
/// serve the rule it exists for.
pub type Result<T, E = Error> = core::result::Result<T, E>;

afd_core::error_shell!(
    /// A fleet-lifecycle failure, with the backtrace of where it was raised.
    pub struct Error(ErrorKind);
);

/// What actually went wrong. Crate-visible so a raise site can name the variant.
#[derive(Debug, thiserror::Error)]
pub(crate) enum ErrorKind {
    #[error("the datastore backing the fleet lifecycle would not answer")]
    Datastore {
        #[source]
        source: afd_db::Error,
    },

    #[error("the credential directory the install checks would not answer")]
    Vault {
        #[source]
        source: afd_vault::Error,
    },

    #[error("the queue backing the fleet lifecycle would not answer")]
    Queue {
        #[source]
        source: afd_redis::Error,
    },

    #[error("statement failed during {context}")]
    Query {
        context: &'static str,
        #[source]
        source: sqlx::Error,
    },

    #[error("core.fleets.{column} holds {stored}, which this build does not know")]
    RowMalformed {
        column: &'static str,
        /// The stored bytes, so the log names what a newer daemon wrote.
        stored: Box<str>,
    },

    #[error("an identifier could not be minted from the current instant")]
    Mint {
        #[source]
        source: afd_core::error::Error,
    },

    #[error("could not draw the entropy a fleet identifier is minted from")]
    Entropy {
        #[source]
        source: afd_crypto::error::Error,
    },

    #[error("the authored TRIGGER.md is not a configuration this daemon can store")]
    Config {
        #[source]
        source: afd_fleet_runtime::Error,
    },

    #[error("the authored SKILL.md frontmatter is not one this daemon can store")]
    Skill {
        #[source]
        source: afd_fleet_runtime::Error,
    },

    #[error("the authored SKILL.md is empty or past its length bound")]
    SkillRejected,

    #[error("the authored TRIGGER.md is empty or past its length bound")]
    TriggerRejected,

    #[error("SKILL.md and TRIGGER.md name different fleets")]
    NameMismatch,

    #[error("this workspace already holds a fleet under the chosen name")]
    NameExists,

    #[error("no fleet with that id lives in this workspace")]
    NotFound,

    #[error("the fleet's current status does not permit that transition")]
    TransitionRefused,

    #[error("a fleet must be killed before it can be purged")]
    MustKillFirst,

    #[error("the caller's If-Match names a source version the row has moved past")]
    SourceStale {
        /// The tag the row holds now, so an editor re-applies in one round trip.
        current: Box<str>,
    },

    #[error("the install could not be finished, and the row was rolled back")]
    InstallRolledBack,

    #[error("no installable library entry matches that id in this workspace")]
    LibraryEntryMissing,

    #[error("the placement tags are outside the bounds a lease can match on")]
    RequiredTagsInvalid,

    #[error("the bundle declares credentials this workspace has not stored")]
    BundleSecretsMissing {
        /// The names, so the refusal can list what to add.
        missing: Vec<String>,
    },
}

impl Error {
    /// The code and the sentence, decided together — see the module note.
    ///
    /// Not `const`: the vault answers for its own failures, and reading its
    /// table means holding a borrow the compiler will not evaluate at compile
    /// time. Deciding a code for it here instead would be this table claiming
    /// to know whether the directory was unreachable or merely refused.
    fn answer(&self) -> (ErrorCode, &'static str) {
        match &self.inner.kind {
            // One code for both stores; their sentences identify the datastore.
            ErrorKind::Datastore { .. } => (
                error_code::INTERNAL_DB_UNAVAILABLE,
                detail::DATABASE_UNAVAILABLE,
            ),
            ErrorKind::Queue { .. } => (
                error_code::INTERNAL_DB_UNAVAILABLE,
                detail::QUEUE_UNAVAILABLE,
            ),
            // The directory answers for itself. An outage there is the same
            // 503 an outage here is, and a failed read is the same 500 — so
            // the code and the sentence come from the vault's own table
            // rather than being decided a second time in this one.
            ErrorKind::Vault { source } => (source.code(), source.detail()),
            // Four internal failures, one fixed sentence: a failed statement, an
            // unreadable row, a clock that cannot name an instant and a host
            // short of entropy are all this process's problem, and naming which
            // would leak the cause to whoever provoked it.
            ErrorKind::Query { .. }
            | ErrorKind::RowMalformed { .. }
            | ErrorKind::Mint { .. }
            | ErrorKind::Entropy { .. } => (error_code::INTERNAL_DB_QUERY, detail::DATABASE_ERROR),
            // A `TRIGGER.md` that failed to parse and one never parsed because
            // it is empty or oversized answer alike: the caller opens the same
            // file either way.
            ErrorKind::Config { .. } | ErrorKind::TriggerRejected => (
                error_code::AGENTSFLEET_INVALID_CONFIG,
                detail::INVALID_CONFIG,
            ),
            // The same code as an unusable `TRIGGER.md`, and a different
            // sentence: both mean "this bundle will not install", and the
            // sentence is what says which of its two documents to open.
            // A document never parsed because it is empty or past its bound
            // answers exactly as one that parsed and failed: the caller's remedy
            // is the same file either way, and a separate code would make a
            // client branch on a distinction it cannot act on.
            ErrorKind::Skill { .. } | ErrorKind::SkillRejected => (
                error_code::AGENTSFLEET_INVALID_CONFIG,
                detail::SKILL_INVALID,
            ),
            ErrorKind::NameMismatch => {
                (error_code::AGENTSFLEET_NAME_MISMATCH, detail::NAME_MISMATCH)
            }
            ErrorKind::NameExists => (error_code::AGENTSFLEET_NAME_EXISTS, detail::NAME_EXISTS),
            ErrorKind::NotFound => (error_code::AGENTSFLEET_NOT_FOUND, detail::NOT_FOUND),
            // One code for two refusals a client acts identically on: a
            // transition the machine rejects, and a purge of a fleet nobody
            // killed first. The sentence says which, and what to do about it.
            ErrorKind::TransitionRefused => (
                error_code::AGENTSFLEET_ALREADY_TERMINAL,
                detail::TRANSITION_REFUSED,
            ),
            ErrorKind::MustKillFirst => (
                error_code::AGENTSFLEET_ALREADY_TERMINAL,
                detail::MUST_KILL_FIRST,
            ),
            ErrorKind::SourceStale { .. } => {
                (error_code::AGENTSFLEET_SOURCE_STALE, detail::SOURCE_STALE)
            }
            ErrorKind::InstallRolledBack => (
                error_code::AGENTSFLEET_INSTALL_ROLLED_BACK,
                detail::INSTALL_ROLLED_BACK,
            ),
            ErrorKind::LibraryEntryMissing => (
                error_code::FLEET_BUNDLE_NOT_FOUND,
                detail::LIBRARY_ENTRY_MISSING,
            ),
            ErrorKind::RequiredTagsInvalid => {
                (error_code::INVALID_REQUEST, detail::REQUIRED_TAGS_INVALID)
            }
            ErrorKind::BundleSecretsMissing { .. } => (
                error_code::FLEET_BUNDLE_SECRETS_MISSING,
                detail::BUNDLE_SECRETS_MISSING,
            ),
        }
    }

    /// The registry code this failure answers with.
    #[must_use]
    pub fn code(&self) -> ErrorCode {
        self.answer().0
    }

    /// The sentence the caller is told.
    #[must_use]
    pub fn detail(&self) -> &'static str {
        self.answer().1
    }

    /// Whether the datastore behind this crate could not be reached.
    ///
    /// The question the HTTP edge turns on: an outage is this instance's
    /// problem to report as a 503, where every other failure here is the
    /// caller's to correct (RULE ECL).
    #[must_use]
    pub fn is_datastore_unavailable(&self) -> bool {
        // Every variant is named rather than falling through a catch-all: a
        // future datastore-backed kind would otherwise classify itself as a
        // 500 in silence, where here it is a compile error until somebody
        // decides. `answer()` above is exhaustive for the same reason.
        match &self.inner.kind {
            ErrorKind::Datastore { .. } | ErrorKind::Queue { .. } => true,
            // The directory is a datastore too, and only it knows whether this
            // was an outage or a read that failed.
            ErrorKind::Vault { source } => source.is_datastore_unavailable(),
            ErrorKind::Query { .. }
            | ErrorKind::RowMalformed { .. }
            | ErrorKind::Mint { .. }
            | ErrorKind::Entropy { .. }
            | ErrorKind::Config { .. }
            | ErrorKind::Skill { .. }
            | ErrorKind::SkillRejected
            | ErrorKind::TriggerRejected
            | ErrorKind::NameMismatch
            | ErrorKind::NameExists
            | ErrorKind::NotFound
            | ErrorKind::TransitionRefused
            | ErrorKind::MustKillFirst
            | ErrorKind::SourceStale { .. }
            | ErrorKind::InstallRolledBack
            | ErrorKind::LibraryEntryMissing
            | ErrorKind::RequiredTagsInvalid
            | ErrorKind::BundleSecretsMissing { .. } => false,
        }
    }

    /// The credentials this workspace has yet to store, when that is why an
    /// install refused.
    ///
    /// `Some` for exactly one kind, like [`Self::stale_tag`]. The 424's body
    /// carries them so an operator is told WHICH secrets to add rather than
    /// diffing the bundle against their own vault by hand.
    #[must_use]
    pub fn missing_secrets(&self) -> Option<&[String]> {
        match &self.inner.kind {
            ErrorKind::BundleSecretsMissing { missing } => Some(missing),
            _not_missing => None,
        }
    }

    /// The tag the row holds now, when this is a stale-source refusal.
    ///
    /// `Some` for exactly one kind. The 412's body carries it so an editor
    /// re-applies without a second round trip to learn what it should have sent.
    #[must_use]
    pub fn stale_tag(&self) -> Option<&str> {
        match &self.inner.kind {
            ErrorKind::SourceStale { current } => Some(current),
            _not_stale => None,
        }
    }
}

#[cfg(test)]
#[path = "error/tests.rs"]
mod tests;
