//! The one error type this crate returns, and the wire code each failure maps to.
//!
//! Same shape as [`afd_db::Error`] and [`afd_fleet::Error`]
//! (`M-ERRORS-CANONICAL-STRUCTS`): a struct carrying a captured backtrace and a
//! private kind, with `is_*` accessors rather than a public enum, so a new
//! internal failure mode is not a breaking change for anyone matching on it.
//!
//! # Why this crate has its own, rather than borrowing the fleet crate's
//!
//! `RUST_ERROR_STANDARD` asks for one error type per crate, and the reason is
//! visible here: the failures below are the tenant plane's whole vocabulary —
//! a name already taken, a login already approved, a credential that must be
//! revoked before it is deleted. None of them can be raised by a lease, a gate
//! or a budget drain, and none of the runner plane's can be raised here. A
//! shared enum would let each side match on arms the other produces, which is
//! exactly the coupling splitting the crates was for.

use std::fmt::{self, Display, Formatter};

use afd_core::error_code::{self, ErrorCode};

pub mod detail;

#[cfg(test)]
mod tests;

pub use self::detail::*;

/// The result every fallible function in this crate returns.
///
/// One alias per crate, defaulted to this crate's own [`Error`], so a reader
/// never has to check WHICH error a signature returns to know it is this one
/// (`RUST_ERROR_STANDARD` rule 1). Written here rather than generated by
/// [`afd_core::error_shell!`] because an alias a reader cannot see does not
/// serve the rule it exists for.
pub type Result<T, E = Error> = core::result::Result<T, E>;

afd_core::error_shell!(
    /// A tenant-plane failure, with the backtrace of where it was raised.
    pub struct Error(ErrorKind);
);

mod kind;

use self::kind::ErrorKind;

/// Which device-flow field a refusal names.
///
/// One kind with a field rather than five kinds, because the five differ in
/// exactly one way — the code and sentence they answer with — and a table
/// keyed on the field says that once. The Zig store spells five error tags and
/// `failFromStoreError` re-pairs each with its code and its sentence at a
/// switch arm, which is the same fact written three times.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SessionField {
    /// The command line's public key, presented at creation.
    PublicKey,
    /// The label the minted credential will carry.
    TokenName,
    /// The relayed envelope the dashboard sealed.
    Ciphertext,
    /// The nonce that envelope was sealed under.
    Nonce,
    /// The six digits a person reads out of the browser.
    VerificationCode,
}

impl Display for SessionField {
    fn fmt(&self, f: &mut Formatter<'_>) -> fmt::Result {
        f.write_str(match self {
            Self::PublicKey => "public_key",
            Self::TokenName => "token_name",
            Self::Ciphertext => "ciphertext",
            Self::Nonce => "nonce",
            Self::VerificationCode => "verification_code",
        })
    }
}

/// Which api-key field a refusal names.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ApiKeyField {
    /// The name the key is listed and grepped under.
    Name,
    /// The free text beside it.
    Description,
}

impl Display for ApiKeyField {
    fn fmt(&self, f: &mut Formatter<'_>) -> fmt::Result {
        f.write_str(match self {
            Self::Name => "key_name",
            Self::Description => "description",
        })
    }
}

impl Error {
    /// Raises `kind` as an error, capturing a backtrace.
    ///
    /// A thin pass through the generated `From<ErrorKind>` — kept because the
    /// raise sites in this crate spell `Error::new(...)`, and the alternative
    /// was editing every one of them to say `.into()` at no gain.
    pub(crate) fn new(kind: ErrorKind) -> Self {
        Self::from(kind)
    }

    /// Whether this is a lost race for one machine's live credential.
    ///
    /// The mint asks, and retries once when it is true. Crate-private: a lost
    /// race is that module's business to resolve, not something a caller should
    /// be branching on.
    pub(crate) const fn is_machine_collision(&self) -> bool {
        matches!(self.inner.kind, ErrorKind::CliCredentialMachineCollision)
    }

    /// Whether the datastore behind this plane could not be reached.
    ///
    /// The question the HTTP edge turns on: an outage is this instance's
    /// problem to report as a 503, where every other failure here is the
    /// caller's to correct.
    #[must_use]
    pub const fn is_datastore_unavailable(&self) -> bool {
        matches!(
            self.inner.kind,
            ErrorKind::Datastore { .. }
                | ErrorKind::Queue { .. }
                | ErrorKind::LibraryPageUnavailable { .. }
        )
    }

    /// The registry code this failure answers with.
    #[must_use]
    pub const fn code(&self) -> ErrorCode {
        match self.inner.kind {
            // One code for both stores. A caller acts identically on either —
            // this instance could not reach what it needed — and which of the
            // two it was belongs in the log beside the request id, not in a
            // code a dashboard would have to branch on.
            ErrorKind::Datastore { .. } | ErrorKind::Queue { .. } => {
                error_code::INTERNAL_DB_UNAVAILABLE
            }
            ErrorKind::Query { .. } | ErrorKind::RowMalformed { .. } => {
                error_code::INTERNAL_DB_QUERY
            }
            // One internal code for four failures the caller shares an
            // inability to correct. Two are this instance's own — a mint that
            // failed, a host that cannot draw entropy. A missing wallet is
            // operator surgery or a defect, because signup bootstrap writes it
            // in the tenant-create transaction; a machine collision reaching
            // the edge means the mint's retry already lost twice in a row. The
            // SENTENCES separate them where separation helps.
            ErrorKind::Mint { .. }
            | ErrorKind::Entropy { .. }
            | ErrorKind::CliCredentialMachineCollision => error_code::INTERNAL_OPERATION_FAILED,
            ErrorKind::SessionFieldInvalid { field } => match field {
                SessionField::PublicKey => error_code::INVALID_PUBLIC_KEY,
                SessionField::TokenName => error_code::INVALID_TOKEN_NAME,
                SessionField::Ciphertext => error_code::INVALID_CIPHERTEXT,
                SessionField::Nonce => error_code::INVALID_NONCE,
                SessionField::VerificationCode => error_code::INVALID_VERIFICATION_CODE,
            },
            ErrorKind::SessionMissing => error_code::SESSION_NOT_FOUND,
            ErrorKind::SessionExpired => error_code::SESSION_EXPIRED,
            ErrorKind::SessionConsumed => error_code::SESSION_CONSUMED,
            // One code for both, and the sentences differ rather than the
            // codes: a client acts identically on either — stop, log in again —
            // and the ceiling is the only one of the two worth naming in prose.
            ErrorKind::SessionAborted | ErrorKind::SessionRateLimited => {
                error_code::SESSION_ABORTED
            }
            ErrorKind::SessionNotApproved => error_code::SESSION_NOT_APPROVED,
            ErrorKind::SessionAlreadyApproved => error_code::SESSION_ALREADY_APPROVED,
            ErrorKind::SessionCodeRejected => error_code::VERIFICATION_FAILED,
            // One code for two refusals from different families, and the
            // SENTENCES are what separate them: a caller who does not own a
            // login session and a subject with no user row are both told they
            // may not proceed, and neither can fix it by re-authenticating.
            ErrorKind::SessionNotOwner | ErrorKind::CliCredentialUnknownSubject => {
                error_code::AUTH_FORBIDDEN
            }
            ErrorKind::ApiKeyFieldInvalid { .. }
            | ErrorKind::CliCredentialMachineNameInvalid
            | ErrorKind::WorkspaceNameInvalid
            | ErrorKind::WorkspaceNameTooLong => error_code::INVALID_REQUEST,
            ErrorKind::WorkspaceNameExists => error_code::WORKSPACE_NAME_EXISTS,
            // A 401 and not a 403: the session's tenant is GONE, so the
            // credential itself is stale and re-authenticating is the remedy.
            ErrorKind::WorkspaceTenantVanished => error_code::AUTH_UNAUTHORIZED,
            // The library family's own transient code, not INTERNAL-001: the
            // catalogue read has carried `UZ-LIBRARY-006` since it shipped,
            // and a dashboard's retry logic may already branch on it.
            ErrorKind::LibraryPageUnavailable { .. } => error_code::LIBRARY_DB_UNAVAILABLE,
            ErrorKind::ApiKeyNotFound => error_code::APIKEY_NOT_FOUND,
            ErrorKind::ApiKeyNameTaken => error_code::APIKEY_NAME_TAKEN,
            ErrorKind::ApiKeyAlreadyRevoked => error_code::APIKEY_ALREADY_REVOKED,
            ErrorKind::ApiKeyReadonlyField => error_code::APIKEY_READONLY_FIELD,
            ErrorKind::ApiKeyMustRevokeFirst => error_code::APIKEY_MUST_REVOKE_FIRST,
            ErrorKind::CliCredentialNotFound => error_code::AUTH_CLI_CREDENTIAL_NOT_FOUND,
        }
    }

    /// The sentence the caller is told.
    ///
    /// A rejection quotes its own detail, because the caller can act on it.
    /// Every internal failure answers a FIXED sentence: one that quoted its
    /// cause would be leaking that cause to whoever provoked it, and the cause
    /// is in the log beside the request id.
    #[must_use]
    pub const fn detail(&self) -> &'static str {
        match self.inner.kind {
            ErrorKind::Datastore { .. } => DETAIL_DATABASE_UNAVAILABLE,
            ErrorKind::Queue { .. } => DETAIL_QUEUE_UNAVAILABLE,
            // Every internal failure answers ONE fixed sentence, deliberately:
            // a statement that failed, a row this daemon cannot read, a clock
            // that cannot name an instant and a host that cannot draw random
            // bytes are all this process's problem, and telling the caller
            // which would be leaking the cause to whoever provoked it. The
            // cause is in the log beside the request id.
            ErrorKind::Query { .. }
            | ErrorKind::RowMalformed { .. }
            | ErrorKind::Mint { .. }
            | ErrorKind::Entropy { .. }
            | ErrorKind::CliCredentialMachineCollision => DETAIL_DATABASE_ERROR,
            ErrorKind::SessionFieldInvalid { field } => match field {
                SessionField::PublicKey => DETAIL_SESSION_PUBLIC_KEY,
                SessionField::TokenName => DETAIL_SESSION_TOKEN_NAME,
                SessionField::Ciphertext => DETAIL_SESSION_CIPHERTEXT,
                SessionField::Nonce => DETAIL_SESSION_NONCE,
                SessionField::VerificationCode => DETAIL_SESSION_CODE_SHAPE,
            },
            ErrorKind::SessionMissing => DETAIL_SESSION_MISSING,
            ErrorKind::SessionExpired => DETAIL_SESSION_EXPIRED,
            ErrorKind::SessionConsumed => DETAIL_SESSION_CONSUMED,
            ErrorKind::SessionAborted => DETAIL_SESSION_ABORTED,
            ErrorKind::SessionRateLimited => DETAIL_SESSION_RATE_LIMITED,
            ErrorKind::SessionNotApproved => DETAIL_SESSION_NOT_APPROVED,
            ErrorKind::SessionAlreadyApproved => DETAIL_SESSION_ALREADY_APPROVED,
            ErrorKind::SessionCodeRejected => DETAIL_SESSION_CODE_REJECTED,
            ErrorKind::SessionNotOwner => DETAIL_SESSION_NOT_OWNER,
            ErrorKind::ApiKeyFieldInvalid { field } => match field {
                ApiKeyField::Name => DETAIL_APIKEY_NAME,
                ApiKeyField::Description => DETAIL_APIKEY_DESCRIPTION,
            },
            ErrorKind::ApiKeyNotFound => DETAIL_APIKEY_NOT_FOUND,
            ErrorKind::ApiKeyNameTaken => DETAIL_APIKEY_NAME_TAKEN,
            ErrorKind::ApiKeyAlreadyRevoked => DETAIL_APIKEY_ALREADY_REVOKED,
            ErrorKind::ApiKeyReadonlyField => DETAIL_APIKEY_READONLY_FIELD,
            ErrorKind::ApiKeyMustRevokeFirst => DETAIL_APIKEY_MUST_REVOKE_FIRST,
            ErrorKind::CliCredentialMachineNameInvalid => DETAIL_CLI_CREDENTIAL_MACHINE_NAME,
            ErrorKind::CliCredentialNotFound => DETAIL_CLI_CREDENTIAL_NOT_FOUND,
            ErrorKind::CliCredentialUnknownSubject => DETAIL_CLI_CREDENTIAL_UNKNOWN_SUBJECT,
            ErrorKind::WorkspaceNameInvalid => DETAIL_WORKSPACE_NAME_INVALID,
            ErrorKind::WorkspaceNameTooLong => DETAIL_WORKSPACE_NAME_TOO_LONG,
            ErrorKind::WorkspaceNameExists => DETAIL_WORKSPACE_NAME_EXISTS,
            ErrorKind::WorkspaceTenantVanished => DETAIL_WORKSPACE_TENANT_VANISHED,
            ErrorKind::LibraryPageUnavailable { .. } => DETAIL_LIBRARY_PAGE_UNAVAILABLE,
        }
    }
}

impl From<afd_db::Error> for Error {
    fn from(source: afd_db::Error) -> Self {
        Self::new(ErrorKind::Datastore { source })
    }
}

impl From<afd_redis::Error> for Error {
    fn from(source: afd_redis::Error) -> Self {
        Self::new(ErrorKind::Queue { source })
    }
}

impl From<afd_core::error::Error> for Error {
    fn from(source: afd_core::error::Error) -> Self {
        Self::new(ErrorKind::Mint { source })
    }
}

impl From<afd_crypto::error::Error> for Error {
    fn from(source: afd_crypto::error::Error) -> Self {
        Self::new(ErrorKind::Entropy { source })
    }
}

mod raise;

pub(crate) use self::raise::*;
