-- Tenant Fleet Library catalog (workspace-scoped, runtime-onboarded).
-- Mirrors core.fleet_bundles (027): UUIDv7 id, workspace_id FK CASCADE,
-- app-set timestamps, no SQL enum checks (RULE STS). Differs from the platform
-- catalog (028) in that it is workspace-scoped and runtime-onboarded by a
-- tenant admin holding the library:write scope. Differs from
-- core.fleet_bundles in that support_files_json stores a path/size/hash
-- manifest only (no support-file body content) and snapshot_key is omitted
-- (the R2 key is derivable from content_hash via importer.snapshotKey).
-- Value sets (source_kind, visibility) are enforced in application code; SQL
-- keeps them as TEXT per the static-string schema rule. Identifiers use UUIDv7
-- values generated by application code.

CREATE TABLE IF NOT EXISTS core.tenant_fleet_library (
    uid                 UUID GENERATED ALWAYS AS (id) STORED PRIMARY KEY,
    CONSTRAINT ck_tenant_fleet_library_uid_uuidv7 CHECK (substring(uid::text from 15 for 1) = '7'),
    id                  UUID NOT NULL UNIQUE,
    workspace_id        UUID NOT NULL REFERENCES core.workspaces(workspace_id) ON DELETE CASCADE,
    name                TEXT NOT NULL,
    -- SKILL.md description, surfaced on the gallery card (M103 Dimension 5.4).
    -- Mirrors core.fleet_library.description; the importer derives it
    -- from the onboarded SKILL frontmatter.
    description         TEXT NOT NULL,
    source_kind         TEXT NOT NULL,
    source_ref          TEXT NOT NULL,
    visibility          TEXT NOT NULL,
    content_hash        TEXT NOT NULL,
    skill_markdown      TEXT NOT NULL,
    trigger_markdown    TEXT,
    support_files_json  JSONB NOT NULL,
    requirements_json   JSONB NOT NULL,
    created_at          BIGINT NOT NULL,
    updated_at          BIGINT NOT NULL,
    CONSTRAINT uq_tenant_fleet_library_ws_hash UNIQUE (workspace_id, content_hash)
);

-- api_runtime onboards (INSERT), reads (SELECT), and updates tenant entries.
GRANT SELECT, INSERT, UPDATE ON core.tenant_fleet_library TO api_runtime;

CREATE INDEX IF NOT EXISTS idx_tenant_fleet_library_ws_created_at
    ON core.tenant_fleet_library(workspace_id, created_at DESC);
