-- Fleet Bundle snapshots: searchable metadata plus immutable source material.
-- Value sets (source_kind, visibility, validation_status) are enforced in
-- application code; SQL keeps them as TEXT per the static-string schema rule.
-- Identifiers use Universally Unique Identifier (UUID) values generated by
-- application code.

CREATE TABLE IF NOT EXISTS core.fleet_bundles (
    uid                 UUID GENERATED ALWAYS AS (id) STORED PRIMARY KEY,
    CONSTRAINT ck_fleet_bundles_uid_uuidv7 CHECK (substring(uid::text from 15 for 1) = '7'),
    id                  UUID NOT NULL UNIQUE,
    workspace_id        UUID NOT NULL REFERENCES core.workspaces(workspace_id) ON DELETE CASCADE,
    name                TEXT NOT NULL,
    source_kind         TEXT NOT NULL,
    source_ref          TEXT NOT NULL,
    visibility          TEXT NOT NULL,
    content_hash        TEXT NOT NULL,
    snapshot_key        TEXT NOT NULL,
    skill_markdown      TEXT NOT NULL,
    trigger_markdown    TEXT,
    support_files_json  JSONB NOT NULL,
    requirements_json   JSONB NOT NULL,
    validation_status   TEXT NOT NULL,
    created_at          BIGINT NOT NULL,
    updated_at          BIGINT NOT NULL,
    CONSTRAINT uq_fleet_bundles_workspace_id_content_hash UNIQUE (workspace_id, content_hash)
);

-- api_runtime imports, previews, reads, and installs bundle snapshots.
GRANT SELECT, INSERT ON core.fleet_bundles TO api_runtime;

CREATE INDEX IF NOT EXISTS idx_fleet_bundles_workspace_id_created_at
    ON core.fleet_bundles(workspace_id, created_at DESC);
