//! The one error type this crate returns, and the wire code each failure maps to.
//!
//! Same shape as `afd_crypto::Error` and `afd_db::Error`: a struct with a
//! private kind and `is_*` accessors, boxed because the largest variant carries
//! a `redis::RedisError` and this type is the `Err` of `Result`s the request
//! path returns.
//!
//! # A missing consumer group is not an outage
//!
//! Dragonfly answers a read against a vanished group with `NOGROUP`, and that is
//! recoverable in one step — recreate the group and read again. Folding it into
//! a generic command failure would lose that, which is why
//! [`Error::is_group_missing`] exists: the reader that owns the restore asks
//! exactly this question, and nothing else has to guess.
//!
//! # A full datastore is not a failed command either
//!
//! `OOM` is the server refusing to grow, and it says something different from
//! every other refusal: the command was fine, the caller was fine, and the
//! answer is to stop sending until something drains. A producer answered with
//! it backs off; a sweeper answered with it stops the pass. Both need to tell
//! it apart from a malformed argument, so [`Error::is_full`] exists (RULE ECL),
//! and the class is never swallowed into "the queue refused".

use afd_core::error_code::{self, ErrorCode};

/// The result every fallible function in this crate returns.
///
/// One alias per crate, defaulted to this crate's own [`Error`], so a reader
/// never has to check WHICH error a signature returns to know it is this one
/// (`RUST_ERROR_STANDARD` rule 1). Written here rather than generated by
/// [`afd_core::error_shell!`] because an alias a reader cannot see does not
/// serve the rule it exists for.
pub type Result<T, E = Error> = core::result::Result<T, E>;

afd_core::error_shell!(
    /// A queue failure, with the backtrace of where it was raised.
    pub struct Error(ErrorKind);
);

/// What actually went wrong. Private so a new variant is not a breaking change.
#[derive(Debug, thiserror::Error)]
pub(crate) enum ErrorKind {
    #[error("{knob} is not set")]
    MissingRedisUrl { knob: &'static str },

    #[error("{knob} must be a redis:// or rediss:// URL")]
    InvalidRedisUrl { knob: &'static str },

    #[error("the TLS certificate authority file {path} could not be read")]
    CaCertUnreadable {
        path: String,
        #[source]
        source: std::io::Error,
    },

    #[error("the {role} Dragonfly configuration was refused before any connection was attempted")]
    ConfigRejected {
        role: &'static str,
        #[source]
        source: Box<redis::RedisError>,
    },

    #[error("the {role} Dragonfly is unreachable")]
    Unreachable {
        role: &'static str,
        #[source]
        source: Box<redis::RedisError>,
    },

    #[error("the {role} Dragonfly presented a certificate the configured authority does not trust")]
    CertificateRejected {
        role: &'static str,
        #[source]
        source: Box<redis::RedisError>,
    },

    #[error("the {role} Dragonfly did not connect within {waited_ms}ms")]
    ConnectTimeout { role: &'static str, waited_ms: u128 },

    #[error("{command} did not answer within {waited_ms}ms")]
    Timeout {
        command: &'static str,
        waited_ms: u128,
    },

    #[error("{command} failed")]
    Command {
        command: &'static str,
        #[source]
        source: Box<redis::RedisError>,
    },

    #[error("the consumer group on {stream} does not exist")]
    GroupMissing { stream: String },

    #[error("the consumer group on {stream} already exists")]
    GroupExists { stream: String },

    /// A stream command addressed a key holding something else.
    ///
    /// Raised by the CALLER, before the command goes out, because the one
    /// command that would provoke it cannot safely be sent: `XGROUP CREATE …
    /// MKSTREAM` creates its key, so it reaches `DbSlice::AddNew`, where
    /// Dragonfly v1.40.2 trips `db_slice.cc:1176 Check failed: res.is_new` and
    /// aborts the node instead of answering. Dragonfly answers `WRONGTYPE`, so this
    /// kind is what a working server owes and this crate supplies.
    ///
    /// Carries no `#[source]`: nothing failed underneath it. The cause is the
    /// `TYPE` reply this crate read and judged, which is the data below
    /// (`RUST_ERROR_STANDARD` rule 4 — `source()` returns what caused you, and
    /// a fabricated reply from a server that was never asked is not a cause).
    #[error("{command} cannot run: {stream} holds a {holds}, not a stream")]
    WrongType {
        command: &'static str,
        stream: String,
        holds: String,
    },

    /// The server refused to grow: `OOM`, the reply a node past its memory
    /// limit gives every write.
    #[error("{command} was refused because the datastore is full")]
    Full { command: &'static str },

    /// A primary admits to evicting keys, which no datastore holding
    /// accepted work may do.
    #[error("primary {node} evicts keys ({setting}); the datastore must retain every key")]
    UnsafeEviction { node: usize, setting: String },

    /// The seed answers as a single server rather than a cluster.
    ///
    /// Every key this crate writes is placed by slot and every script it
    /// runs is single-slot by construction. A deployment with no slots to
    /// route by is not one this daemon can serve, and the only honest
    /// moment to say so is before the first write.
    #[error(
        "the datastore is not a cluster (cluster_enabled:{reported}); this daemon routes every key by slot"
    )]
    NotACluster { reported: String },

    /// The server does not know a command this daemon's design requires.
    #[error("the datastore does not support {command}, which this daemon requires")]
    MissingCapability { command: &'static str },

    #[error("a {what} reply was not the shape this client expects")]
    UnexpectedReply { what: &'static str },

    #[error("the subscription hub's connection is gone")]
    HubClosed,
}

impl Error {
    /// Raises `kind` as an error, capturing a backtrace.
    ///
    /// A thin pass through the generated `From<ErrorKind>` — kept because the
    /// raise sites in this crate spell `Error::new(...)`, and the alternative
    /// was editing every one of them to say `.into()` at no gain.
    pub(crate) fn new(kind: ErrorKind) -> Self {
        Self::from(kind)
    }

    /// Whether a role's URL or certificate path was absent or malformed.
    #[must_use]
    pub fn is_config(&self) -> bool {
        matches!(
            self.inner.kind,
            ErrorKind::MissingRedisUrl { .. }
                | ErrorKind::InvalidRedisUrl { .. }
                | ErrorKind::CaCertUnreadable { .. }
                | ErrorKind::ConfigRejected { .. }
        )
    }

    /// Whether Dragonfly could not be reached, or did not answer in time.
    #[must_use]
    pub fn is_unavailable(&self) -> bool {
        matches!(
            self.inner.kind,
            ErrorKind::Unreachable { .. }
                | ErrorKind::CertificateRejected { .. }
                | ErrorKind::ConnectTimeout { .. }
                | ErrorKind::Timeout { .. }
        )
    }

    /// Whether the server's certificate was not trusted by the configured
    /// authority.
    ///
    /// A narrowing of [`Self::is_unavailable`], not a peer of it: the
    /// datastore is unusable either way, and this says which of the two
    /// places to go looking. A question rather than a substring of an error
    /// message, for the reason [`Self::is_group_exists`] gives — the driver
    /// stringifies the cause it was handed, so the text is the least stable
    /// thing about this failure.
    #[must_use]
    pub fn is_certificate_rejected(&self) -> bool {
        matches!(self.inner.kind, ErrorKind::CertificateRejected { .. })
    }

    /// Whether a command was refused rather than prevented by an outage.
    ///
    /// [`ErrorKind::WrongType`] is claimed here although it never reaches the
    /// wire: a caller's question is "did the datastore refuse my command, or is
    /// it unreachable?", and a create this crate declined on the server's behalf
    /// answers the first. Leaving it unclaimed would put it outside every
    /// accessor, which is a kind nobody can handle — the thing
    /// `test_the_accessors_partition_the_kinds` exists to prevent.
    #[must_use]
    pub fn is_command(&self) -> bool {
        matches!(
            self.inner.kind,
            ErrorKind::Command { .. }
                | ErrorKind::UnexpectedReply { .. }
                | ErrorKind::WrongType { .. }
        )
    }

    /// Whether the stream's consumer group has gone missing.
    ///
    /// Recoverable in one step, and the only failure here that is. See the
    /// module documentation.
    #[must_use]
    pub fn is_group_missing(&self) -> bool {
        matches!(self.inner.kind, ErrorKind::GroupMissing { .. })
    }

    /// Whether the consumer group is already there.
    ///
    /// The expected answer to an idempotent create, not a failure — which is
    /// why it is a question and not a substring of an error message. Reading it
    /// off `Display` was the first attempt, and it did not work: `Display`
    /// renders the kind, and the Dragonfly code lives on the source.
    #[must_use]
    pub fn is_group_exists(&self) -> bool {
        matches!(self.inner.kind, ErrorKind::GroupExists { .. })
    }

    /// Whether the hub was shut down while a subscriber was waiting.
    #[must_use]
    pub fn is_hub_closed(&self) -> bool {
        matches!(self.inner.kind, ErrorKind::HubClosed)
    }

    /// Whether the datastore refused to grow.
    ///
    /// The backpressure class: the server answered, the command was
    /// well-formed, and the only cure is for something to drain. A caller
    /// that retries immediately makes it worse; one that reports it as a
    /// generic command failure sends an operator to the wrong place.
    #[must_use]
    pub fn is_full(&self) -> bool {
        matches!(self.inner.kind, ErrorKind::Full { .. })
    }

    /// Whether a primary was found evicting keys at preflight.
    #[must_use]
    pub fn is_unsafe_eviction(&self) -> bool {
        matches!(self.inner.kind, ErrorKind::UnsafeEviction { .. })
    }

    /// Whether boot refused the datastore for what it IS: a single server
    /// where a cluster is required, or a server missing a command this
    /// daemon needs.
    ///
    /// Apart from [`Self::is_unsafe_eviction`] on purpose, which names a
    /// datastore this daemon COULD serve, configured so that it must not.
    /// One is answered by pointing at a different datastore or upgrading
    /// this one; the other by changing a setting on it.
    #[must_use]
    pub fn is_unsuitable_datastore(&self) -> bool {
        matches!(
            self.inner.kind,
            ErrorKind::NotACluster { .. } | ErrorKind::MissingCapability { .. }
        )
    }

    /// The registry code a handler would surface for this failure.
    ///
    /// A full datastore answers the UNAVAILABLE code rather than the
    /// operation-failed one: to the producer being refused it is a
    /// datastore that cannot take the write right now, and the retry
    /// behaviour that code carries is the one wanted. The class stays
    /// separable through [`Self::is_full`].
    #[must_use]
    pub fn code(&self) -> ErrorCode {
        match self.inner.kind {
            ErrorKind::Command { .. }
            | ErrorKind::UnexpectedReply { .. }
            | ErrorKind::GroupMissing { .. }
            | ErrorKind::GroupExists { .. }
            | ErrorKind::WrongType { .. } => error_code::INTERNAL_OPERATION_FAILED,
            ErrorKind::Full { .. } => error_code::INTERNAL_DB_UNAVAILABLE,
            _ => error_code::STARTUP_REDIS_CONNECT,
        }
    }
}

/// The reply codes pulled out of a failed command by name (RULE UFS).
///
/// `NOGROUP` is the one recoverable failure: the group vanished (deleted out
/// of band, a restart without persistence, a failover to an empty replica)
/// and recreating it is a defined repair. `OOM` is the one that is not a
/// fault at all but a limit. Dragonfly reports both as ordinary error replies, so
/// nothing else would tell them apart from a genuine command failure.
const CODE_NO_GROUP: &str = "NOGROUP";
const CODE_BUSY_GROUP: &str = "BUSYGROUP";
const CODE_OUT_OF_MEMORY: &str = "OOM";

/// Classifies a failed command — see the three codes above.
pub(crate) fn classify(command: &'static str, stream: &str, source: redis::RedisError) -> Error {
    match source.code() {
        Some(CODE_NO_GROUP) => {
            return Error::new(ErrorKind::GroupMissing {
                stream: stream.to_owned(),
            });
        }
        Some(CODE_BUSY_GROUP) => {
            return Error::new(ErrorKind::GroupExists {
                stream: stream.to_owned(),
            });
        }
        Some(CODE_OUT_OF_MEMORY) => return Error::new(ErrorKind::Full { command }),
        _ => {}
    }
    if source.is_connection_dropped() || source.is_io_error() {
        return Error::new(ErrorKind::Unreachable {
            role: "default",
            source: Box::new(source),
        });
    }
    Error::new(ErrorKind::Command {
        command,
        source: Box::new(source),
    })
}

/// The `WRONGTYPE` a working server owes, raised by the caller instead.
///
/// `FleetStreams` and `OutboundQueue` ask `TYPE` before any `MKSTREAM` create
/// and call this when the answer rules the command out — see
/// [`ErrorKind::WrongType`] for why the command cannot simply be sent and let
/// the server refuse it.
pub(crate) fn wrong_type(command: &'static str, stream: &str, holds: &str) -> Error {
    Error::new(ErrorKind::WrongType {
        command,
        stream: stream.to_owned(),
        holds: holds.to_owned(),
    })
}

/// A command that never answered inside its deadline.
pub(crate) fn timed_out(command: &'static str, waited_ms: u128) -> Error {
    Error::new(ErrorKind::Timeout { command, waited_ms })
}

/// A datastore that could not be reached at all.
///
/// Here rather than at the call site so the three ways a dial can end —
/// unreachable, refused for trust, refused for configuration — are raised
/// through one seam instead of two constructors and a hand-rolled
/// `Error::new`.
pub(crate) fn unreachable(role: &'static str, source: redis::RedisError) -> Error {
    Error::new(ErrorKind::Unreachable {
        role,
        source: Box::new(source),
    })
}

/// A seed or certificate the driver refused before opening any socket.
///
/// Deliberately not [`ErrorKind::InvalidRedisUrl`]: the client is built from
/// the seed AND the certificate bytes, and a build that fails has not said
/// which. Naming the URL would be a guess, and a guess in an error message is
/// how an operator ends up reading the wrong file. The driver's own reason
/// stays on the source.
pub(crate) fn config_rejected(role: &'static str, source: redis::RedisError) -> Error {
    Error::new(ErrorKind::ConfigRejected {
        role,
        source: Box::new(source),
    })
}

/// A TLS endpoint whose certificate the configured authority does not trust.
///
/// Separate from [`ErrorKind::Unreachable`] because the two send an operator
/// to opposite places: unreachable is a port, a firewall or a dead process,
/// and this is the authority they configured. Both are still
/// [`Error::is_unavailable`] — the datastore is equally unusable either way,
/// and a caller branching on availability should not have to learn a new kind
/// to keep working.
pub(crate) fn certificate_rejected(role: &'static str, source: redis::RedisError) -> Error {
    Error::new(ErrorKind::CertificateRejected {
        role,
        source: Box::new(source),
    })
}

/// A connection that did not finish inside its whole-operation budget.
pub(crate) fn connect_timed_out(role: &'static str, waited_ms: u128) -> Error {
    Error::new(ErrorKind::ConnectTimeout { role, waited_ms })
}

/// A reply whose shape the client does not recognise.
pub(crate) fn unexpected_reply(what: &'static str) -> Error {
    Error::new(ErrorKind::UnexpectedReply { what })
}

/// One error of every kind, for tests that walk the whole surface.
///
/// Same seam and same argument as `afd_db::error::one_of_each_kind`: these are
/// the renderings a human reads while something is already wrong, and a Dragonfly
/// that refuses a command on demand is not something a test can arrange for
/// every kind.
#[cfg(feature = "test-util")]
#[must_use]
#[expect(
    clippy::expect_used,
    reason = "a sample builder whose own preconditions fail should stop the suite"
)]
pub fn one_of_each_kind() -> Vec<(&'static str, Error)> {
    // One server-side refusal, built the way the wire builds one, because the
    // code is the whole difference between a command the server would not run
    // and a server that would not grow.
    //
    // Parsed from a RESP error reply rather than assembled from
    // `RedisError::from((ErrorKind::Extension, code, detail))`. That
    // constructor LOOKS like it carries the code and does not: it produces a
    // `General` repr, whose `code()` is always `None`. Every sample routed
    // through `classify` therefore fell past all three code arms and came back
    // a plain command failure — including the one labelled `full`, so this
    // function promised one of each kind and held no `Full` at all, and
    // `afd_admission`'s error suite panicked looking for it. Parse-then-extract
    // is the route the driver itself takes — the parser answers an error reply
    // as `Value::ServerError` so a caller can find one nested in an array, and
    // `extract_error` is what turns it into the `Err` a command sees — so the
    // code survives and `classify` is exercised instead of bypassed.
    let refusal = |code: &str| -> redis::RedisError {
        let reply = format!("-{code} the server said no\r\n");
        redis::parse_redis_value(reply.as_bytes())
            .and_then(redis::Value::extract_error)
            .expect_err("a RESP error reply extracts as an error, not a value")
    };

    vec![
        (
            "missing url",
            Error::new(ErrorKind::MissingRedisUrl {
                knob: "DRAGONFLY_URL",
            }),
        ),
        (
            "invalid url",
            Error::new(ErrorKind::InvalidRedisUrl {
                knob: "DRAGONFLY_URL",
            }),
        ),
        (
            "ca cert unreadable",
            Error::new(ErrorKind::CaCertUnreadable {
                path: "/tls/ca.crt".to_owned(),
                source: std::io::Error::from(std::io::ErrorKind::NotFound),
            }),
        ),
        (
            "unreachable",
            Error::new(ErrorKind::Unreachable {
                role: "default",
                source: Box::new(refusal("refused")),
            }),
        ),
        (
            "certificate rejected",
            certificate_rejected("default", refusal("refused")),
        ),
        (
            "config rejected",
            config_rejected("default", refusal("refused")),
        ),
        ("connect timeout", connect_timed_out("default", 5_000)),
        ("timeout", timed_out("XADD", 5_000)),
        (
            "command",
            classify("XADD", "fleet:x:events", refusal("refused")),
        ),
        (
            "wrong type",
            wrong_type("XGROUP", "fleet:x:events", "string"),
        ),
        (
            "group missing",
            Error::new(ErrorKind::GroupMissing {
                stream: "fleet:x:events".to_owned(),
            }),
        ),
        (
            "group exists",
            Error::new(ErrorKind::GroupExists {
                stream: "fleet:x:events".to_owned(),
            }),
        ),
        (
            "full",
            classify("XADD", "fleet:x:events", refusal(CODE_OUT_OF_MEMORY)),
        ),
        (
            "unsafe eviction",
            Error::new(ErrorKind::UnsafeEviction {
                node: 0,
                setting: "maxmemory_policy=allkeys-lru".to_owned(),
            }),
        ),
        (
            "not a cluster",
            Error::new(ErrorKind::NotACluster {
                reported: "0".to_owned(),
            }),
        ),
        (
            "missing capability",
            Error::new(ErrorKind::MissingCapability {
                command: "SSUBSCRIBE",
            }),
        ),
        ("unexpected reply", unexpected_reply("PING")),
        ("hub closed", Error::new(ErrorKind::HubClosed)),
    ]
}
