//! The one error type this crate returns, and the wire code each failure maps to.
//!
//! Same shape as `afd_crypto::Error` and `afd_db::Error`: a struct with a
//! private kind and `is_*` accessors, boxed because the largest variant carries
//! a `redis::RedisError` and this type is the `Err` of `Result`s the request
//! path returns.
//!
//! # A missing consumer group is not an outage
//!
//! Dragonfly answers a read against a vanished group with `NOGROUP`, and that is
//! recoverable in one step — recreate the group and read again. Folding it into
//! a generic command failure would lose that, which is why
//! [`Error::is_group_missing`] exists: the reader that owns the restore asks
//! exactly this question, and nothing else has to guess.
//!
//! # A full datastore is not a failed command either
//!
//! `OOM` is the server refusing to grow, and it says something different from
//! every other refusal: the command was fine, the caller was fine, and the
//! answer is to stop sending until something drains. A producer answered with
//! it backs off; a sweeper answered with it stops the pass. Both need to tell
//! it apart from a malformed argument, so [`Error::is_full`] exists (RULE ECL),
//! and the class is never swallowed into "the queue refused".

use afd_core::error_code::{self, ErrorCode};

mod raise;
#[cfg(feature = "test-util")]
mod samples;

pub(crate) use self::raise::{
    certificate_rejected, classify, config_rejected, connect_timed_out, timed_out,
    unexpected_reply, unreachable, wrong_type,
};
#[cfg(feature = "test-util")]
pub use self::samples::one_of_each_kind;

/// The result every fallible function in this crate returns.
///
/// One alias per crate, defaulted to this crate's own [`Error`], so a reader
/// never has to check WHICH error a signature returns to know it is this one
/// (`RUST_ERROR_STANDARD` rule 1). Written here rather than generated by
/// [`afd_core::error_shell!`] because an alias a reader cannot see does not
/// serve the rule it exists for.
pub type Result<T, E = Error> = core::result::Result<T, E>;

afd_core::error_shell!(
    /// A queue failure, with the backtrace of where it was raised.
    pub struct Error(ErrorKind);
);

/// What actually went wrong. Private so a new variant is not a breaking change.
#[derive(Debug, thiserror::Error)]
pub(crate) enum ErrorKind {
    #[error("{knob} is not set")]
    MissingUrl { knob: &'static str },

    #[error("{knob} must be a redis:// or rediss:// URL")]
    InvalidUrl { knob: &'static str },

    #[error("the TLS certificate authority file {path} could not be read")]
    CaCertUnreadable {
        path: String,
        #[source]
        source: std::io::Error,
    },

    #[error("the {role} Dragonfly configuration was refused before any connection was attempted")]
    ConfigRejected {
        role: &'static str,
        #[source]
        source: Box<redis::RedisError>,
    },

    #[error("the {role} Dragonfly is unreachable")]
    Unreachable {
        role: &'static str,
        #[source]
        source: Box<redis::RedisError>,
    },

    #[error("the {role} Dragonfly presented a certificate the configured authority does not trust")]
    CertificateRejected {
        role: &'static str,
        #[source]
        source: Box<redis::RedisError>,
    },

    #[error("the {role} Dragonfly did not connect within {waited_ms}ms")]
    ConnectTimeout { role: &'static str, waited_ms: u128 },

    #[error("{command} did not answer within {waited_ms}ms")]
    Timeout {
        command: &'static str,
        waited_ms: u128,
    },

    #[error("{command} failed")]
    Command {
        command: &'static str,
        #[source]
        source: Box<redis::RedisError>,
    },

    #[error("the consumer group on {stream} does not exist")]
    GroupMissing { stream: String },

    #[error("the consumer group on {stream} already exists")]
    GroupExists { stream: String },

    /// A stream command addressed a key holding something else.
    ///
    /// Raised by the CALLER, before the command goes out, because the one
    /// command that would provoke it cannot safely be sent: `XGROUP CREATE …
    /// MKSTREAM` creates its key, so it reaches `DbSlice::AddNew`, where
    /// Dragonfly v1.40.2 trips `db_slice.cc:1176 Check failed: res.is_new` and
    /// aborts the node instead of answering. Dragonfly answers `WRONGTYPE`, so this
    /// kind is what a working server owes and this crate supplies.
    ///
    /// Carries no `#[source]`: nothing failed underneath it. The cause is the
    /// `TYPE` reply this crate read and judged, which is the data below
    /// (`RUST_ERROR_STANDARD` rule 4 — `source()` returns what caused you, and
    /// a fabricated reply from a server that was never asked is not a cause).
    #[error("{command} cannot run: {stream} holds a {holds}, not a stream")]
    WrongType {
        command: &'static str,
        stream: String,
        holds: String,
    },

    /// The server refused to grow: `OOM`, the reply a node past its memory
    /// limit gives every write.
    #[error("{command} was refused because the datastore is full")]
    Full { command: &'static str },

    /// A primary admits to evicting keys, which no datastore holding
    /// accepted work may do.
    #[error("primary {node} evicts keys ({setting}); the datastore must retain every key")]
    UnsafeEviction { node: usize, setting: String },

    /// The seed answers as a single server rather than a cluster.
    ///
    /// Every key this crate writes is placed by slot and every script it
    /// runs is single-slot by construction. A deployment with no slots to
    /// route by is not one this daemon can serve, and the only honest
    /// moment to say so is before the first write.
    #[error(
        "the datastore is not a cluster (cluster_enabled:{reported}); this daemon routes every key by slot"
    )]
    NotACluster { reported: String },

    /// The server does not know a command this daemon's design requires.
    #[error("the datastore does not support {command}, which this daemon requires")]
    MissingCapability { command: &'static str },

    #[error("a {what} reply was not the shape this client expects")]
    UnexpectedReply { what: &'static str },

    #[error("the subscription hub's connection is gone")]
    HubClosed,

    /// The entropy a readiness token is minted from could not be drawn.
    #[error("the entropy a readiness token is minted from could not be drawn")]
    Entropy {
        #[source]
        source: afd_crypto::error::Error,
    },

    /// A readiness token could not be minted from the current instant.
    #[error("a readiness token could not be minted")]
    Identifier {
        #[source]
        source: afd_core::error::Error,
    },
}

afd_core::error_lifts!(Error, ErrorKind:
    afd_crypto::error::Error => Entropy,
    afd_core::error::Error => Identifier,
);

impl Error {
    /// Raises `kind` as an error, capturing a backtrace.
    ///
    /// A thin pass through the generated `From<ErrorKind>` — kept because the
    /// raise sites in this crate spell `Error::new(...)`, and the alternative
    /// was editing every one of them to say `.into()` at no gain.
    pub(crate) fn new(kind: ErrorKind) -> Self {
        Self::from(kind)
    }

    /// Whether a role's URL or certificate path was absent or malformed.
    #[must_use]
    pub fn is_config(&self) -> bool {
        matches!(
            self.inner.kind,
            ErrorKind::MissingUrl { .. }
                | ErrorKind::InvalidUrl { .. }
                | ErrorKind::CaCertUnreadable { .. }
                | ErrorKind::ConfigRejected { .. }
        )
    }

    /// Whether Dragonfly could not be reached, or did not answer in time.
    #[must_use]
    pub fn is_unavailable(&self) -> bool {
        matches!(
            self.inner.kind,
            ErrorKind::Unreachable { .. }
                | ErrorKind::CertificateRejected { .. }
                | ErrorKind::ConnectTimeout { .. }
                | ErrorKind::Timeout { .. }
        )
    }

    /// Whether the server's certificate was not trusted by the configured
    /// authority.
    ///
    /// A narrowing of [`Self::is_unavailable`], not a peer of it: the
    /// datastore is unusable either way, and this says which of the two
    /// places to go looking. A question rather than a substring of an error
    /// message, for the reason [`Self::is_group_exists`] gives — the driver
    /// stringifies the cause it was handed, so the text is the least stable
    /// thing about this failure.
    #[must_use]
    pub fn is_certificate_rejected(&self) -> bool {
        matches!(self.inner.kind, ErrorKind::CertificateRejected { .. })
    }

    /// Whether a command was refused rather than prevented by an outage.
    ///
    /// [`ErrorKind::WrongType`] is claimed here although it never reaches the
    /// wire: a caller's question is "did the datastore refuse my command, or is
    /// it unreachable?", and a create this crate declined on the server's behalf
    /// answers the first. Leaving it unclaimed would put it outside every
    /// accessor, which is a kind nobody can handle — the thing
    /// `test_the_accessors_partition_the_kinds` exists to prevent.
    #[must_use]
    pub fn is_command(&self) -> bool {
        matches!(
            self.inner.kind,
            ErrorKind::Command { .. }
                | ErrorKind::UnexpectedReply { .. }
                | ErrorKind::WrongType { .. }
        )
    }

    /// Whether the stream's consumer group has gone missing.
    ///
    /// Recoverable in one step, and the only failure here that is. See the
    /// module documentation.
    #[must_use]
    pub fn is_group_missing(&self) -> bool {
        matches!(self.inner.kind, ErrorKind::GroupMissing { .. })
    }

    /// Whether the consumer group is already there.
    ///
    /// The expected answer to an idempotent create, not a failure — which is
    /// why it is a question and not a substring of an error message. Reading it
    /// off `Display` was the first attempt, and it did not work: `Display`
    /// renders the kind, and the Dragonfly code lives on the source.
    #[must_use]
    pub fn is_group_exists(&self) -> bool {
        matches!(self.inner.kind, ErrorKind::GroupExists { .. })
    }

    /// Whether the hub was shut down while a subscriber was waiting.
    #[must_use]
    pub fn is_hub_closed(&self) -> bool {
        matches!(self.inner.kind, ErrorKind::HubClosed)
    }

    /// Whether the datastore refused to grow.
    ///
    /// The backpressure class: the server answered, the command was
    /// well-formed, and the only cure is for something to drain. A caller
    /// that retries immediately makes it worse; one that reports it as a
    /// generic command failure sends an operator to the wrong place.
    #[must_use]
    pub fn is_full(&self) -> bool {
        matches!(self.inner.kind, ErrorKind::Full { .. })
    }

    /// Whether a primary was found evicting keys at preflight.
    #[must_use]
    pub fn is_unsafe_eviction(&self) -> bool {
        matches!(self.inner.kind, ErrorKind::UnsafeEviction { .. })
    }

    /// Whether boot refused the datastore for what it IS: a single server
    /// where a cluster is required, or a server missing a command this
    /// daemon needs.
    ///
    /// Apart from [`Self::is_unsafe_eviction`] on purpose, which names a
    /// datastore this daemon COULD serve, configured so that it must not.
    /// One is answered by pointing at a different datastore or upgrading
    /// this one; the other by changing a setting on it.
    #[must_use]
    pub fn is_unsuitable_datastore(&self) -> bool {
        matches!(
            self.inner.kind,
            ErrorKind::NotACluster { .. } | ErrorKind::MissingCapability { .. }
        )
    }

    /// Whether a readiness token could not be minted: the host refused its
    /// entropy, or its clock sits outside what a version-7 identifier carries.
    ///
    /// Neither the datastore nor the command is at fault, so neither
    /// [`Self::is_unavailable`] nor [`Self::is_command`] claims it.
    #[must_use]
    pub fn is_unmintable(&self) -> bool {
        matches!(
            self.inner.kind,
            ErrorKind::Entropy { .. } | ErrorKind::Identifier { .. }
        )
    }

    /// The registry code a handler would surface for this failure.
    ///
    /// A full datastore answers the UNAVAILABLE code rather than the
    /// operation-failed one: to the producer being refused it is a
    /// datastore that cannot take the write right now, and the retry
    /// behaviour that code carries is the one wanted. The class stays
    /// separable through [`Self::is_full`].
    #[must_use]
    pub fn code(&self) -> ErrorCode {
        match self.inner.kind {
            ErrorKind::Command { .. }
            | ErrorKind::UnexpectedReply { .. }
            | ErrorKind::GroupMissing { .. }
            | ErrorKind::GroupExists { .. }
            | ErrorKind::WrongType { .. }
            | ErrorKind::Entropy { .. }
            | ErrorKind::Identifier { .. } => error_code::INTERNAL_OPERATION_FAILED,
            ErrorKind::Full { .. } => error_code::INTERNAL_DB_UNAVAILABLE,
            _ => error_code::STARTUP_DRAGONFLY_CONNECT,
        }
    }
}
