//! Shared offline auth fixtures for the integration suite — ONE committed
//! keypair + a fixed set of PERSONAS, so the JWKS can't drift per-file and a
//! scope change is a one-line edit in scripts/mint-scope-personas.mjs.
//!
//! Personas (scope sets):
//!   VIEWER          fleet:read
//!   OPERATOR        fleet:write credential:read
//!   TENANT_ADMIN    fleet:admin credential:write apikey:admin fleetkey:write grant:write connector:write billing:read approval:resolve workspace:admin template:write
//!   PLATFORM_ADMIN  runner:enroll runner:read runner:write stream:read model:admin platform-key:admin template:admin workspace:any
//!   NO_TENANT       fleet:admin credential:write apikey:admin fleetkey:write grant:write connector:write billing:read approval:resolve workspace:admin template:write
//!
//! Regenerate with: node scripts/mint-scope-personas.mjs --apply

pub const ISSUER = "https://clerk.test.agentsfleet.net";
pub const AUDIENCE = "https://api.agentsfleet.net";
pub const JWKS =
    \\{"keys":[{"kty":"RSA","n":"w2oFSV7rG1xjHczXGPcK1xDj1i5FYceHf8ZgBuM4czvrTQ70eQLVrArD5pPL0WFyE9WGQC8UjOumKUNctO2MPIW7q0ncnFXzDDczkHeTnxPDyPJX5yeA6GdEbkGm0HkCrPFFqdf69lpzuuEsCwd1rLX_Iq7WNoLYJ4AysF5Ypcd4jVRw4LhseQZ4KcME5gpb-EvOS5Lo6z_T2ZEiktVW7YE_OVKWOlJ-9ot1NCfCufH1nV1q3rN5vAngijxzxFRoWsdhuuHdzOH8xJiYTidSTFiLMKVMxunMqrSTdJqwhLyGkBYJvH_xwCmGAtKA0-uIeO-3eBYDwS1Fs2LgzegdDw","e":"AQAB","kid":"test-kid-static","use":"sig","alg":"RS256"}]}
;

/// Persona — see scopes in the module header. Minted by scripts/mint-scope-personas.mjs.
pub const VIEWER =
    "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InRlc3Qta2lkLXN0YXRpYyJ9.eyJzdWIiOiJ1c2VyX3Rlc3QiLCJpc3MiOiJodHRwczovL2NsZXJrLnRlc3QuYWdlbnRzZmxlZXQubmV0IiwiYXVkIjoiaHR0cHM6Ly9hcGkuYWdlbnRzZmxlZXQubmV0IiwiZXhwIjo0MTAyNDQ0ODAwLCJzY29wZXMiOiJmbGVldDpyZWFkIiwibWV0YWRhdGEiOnsidGVuYW50X2lkIjoiMDE5NWI0YmEtOGQzYS03ZjEzLThhYmMtMmIzZTFlMGE2ZjAxIiwid29ya3NwYWNlX2lkIjoiMDE5NWI0YmEtOGQzYS03ZjEzLThhYmMtMmIzZTFlMGE2ZjExIn19.BNAMRRdD7GPXBQBGeCZbYV2cOVrnNDIlwhq0TKWv7XRfcRO-7RUJ-L1wYNrTWQTAWFg13t28gq1a1IdrPiFfVq3fce5A2RkaA15EH7Lqd65WHtZ3ydAuLpVstKQQIm_VdMtDdfBGY2p5p7FlcJ8MVAtLkcTDqnkyvb_aJZaR7oSkMbhizPKx5B7GUSOuz5xR8sMJEbkSSavU6_EiLQlrIIRu71bIQ-gG_QzjIFMC4hBkBQJKTWJ44AfTbjOy8K58qLRvWx_Aox0OKs5MY30InhDFqcbaE8H0C6heOuiSGP0BjiCs5rNpGiwFG4FlzZF6bIWdYkH_uvuc1OYxOk0sfw";
/// Persona — see scopes in the module header. Minted by scripts/mint-scope-personas.mjs.
pub const OPERATOR =
    "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InRlc3Qta2lkLXN0YXRpYyJ9.eyJzdWIiOiJ1c2VyX3Rlc3QiLCJpc3MiOiJodHRwczovL2NsZXJrLnRlc3QuYWdlbnRzZmxlZXQubmV0IiwiYXVkIjoiaHR0cHM6Ly9hcGkuYWdlbnRzZmxlZXQubmV0IiwiZXhwIjo0MTAyNDQ0ODAwLCJzY29wZXMiOiJmbGVldDp3cml0ZSBjcmVkZW50aWFsOnJlYWQiLCJtZXRhZGF0YSI6eyJ0ZW5hbnRfaWQiOiIwMTk1YjRiYS04ZDNhLTdmMTMtOGFiYy0yYjNlMWUwYTZmMDEiLCJ3b3Jrc3BhY2VfaWQiOiIwMTk1YjRiYS04ZDNhLTdmMTMtOGFiYy0yYjNlMWUwYTZmMTEifX0.RFmtgXgg0PsJMoilAZQ5Cc-GMCcIr_N-aoDth9Vyzr8UK7nEe9LasIcypM-GXz6rt6WTila0iyFe07ZOX0KWV2eW96SQnAL_j8l5K2hSodUCQbspKByEa9iytaTCSY9WCTlD1S88hP73TymVNrdykh6wVhcYHjGrEOmBr1N9rFSv1YzF1zDBda2JDw8MrtOpi9fQQv794amXfaFSY9yAk_2iKDU8XHwSzyewS2imIWT9zNs4uaF5wZFmBIbGL3eVTTJ2v2wdURTmq2Yre8n57K3jkKoWhsEEx-1_wgVGG7HPKo8bkYn7k4bbxgy7bHVMtiF4_kxKWZXN3winoCb1Wg";
/// Persona — see scopes in the module header. Minted by scripts/mint-scope-personas.mjs.
pub const TENANT_ADMIN =
    "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InRlc3Qta2lkLXN0YXRpYyJ9.eyJzdWIiOiJ1c2VyX3Rlc3QiLCJpc3MiOiJodHRwczovL2NsZXJrLnRlc3QuYWdlbnRzZmxlZXQubmV0IiwiYXVkIjoiaHR0cHM6Ly9hcGkuYWdlbnRzZmxlZXQubmV0IiwiZXhwIjo0MTAyNDQ0ODAwLCJzY29wZXMiOiJmbGVldDphZG1pbiBjcmVkZW50aWFsOndyaXRlIGFwaWtleTphZG1pbiBmbGVldGtleTp3cml0ZSBncmFudDp3cml0ZSBjb25uZWN0b3I6d3JpdGUgYmlsbGluZzpyZWFkIGFwcHJvdmFsOnJlc29sdmUgd29ya3NwYWNlOmFkbWluIHRlbXBsYXRlOndyaXRlIiwibWV0YWRhdGEiOnsidGVuYW50X2lkIjoiMDE5NWI0YmEtOGQzYS03ZjEzLThhYmMtMmIzZTFlMGE2ZjAxIiwid29ya3NwYWNlX2lkIjoiMDE5NWI0YmEtOGQzYS03ZjEzLThhYmMtMmIzZTFlMGE2ZjExIn19.kVRAj6glWRk8fqs0angPNi24xATO7DCFm9R4ZxlOtqqCRmwZcuhc49AbEz0YD4-8kL7-G5YaqZBgEGr95nGJyd8cxvO1CJhv9Ncl7_iDO6cyAPEX7f1vQggT_iIwANuaoF3tXsuIl3xufC397Ueq4C-x02UeXPNEskEvEty5qCQwkzg9-98R554iXznhilYh5bgzpgtstBUpdgCPGr8-plyNjeANNTzNarG2SbwLcsIT1ZV0CPiVAbykUfj35NF7hn-ZcpRby7moSV0vGp2kvJMJMiyFN2Ol5WUCGa8DFZykf60A-zpKJn_aErIwggGo9oTWgPmDFbkPX0Z_I2jRLA";
/// Persona — see scopes in the module header. Minted by scripts/mint-scope-personas.mjs.
pub const PLATFORM_ADMIN =
    "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InRlc3Qta2lkLXN0YXRpYyJ9.eyJzdWIiOiJ1c2VyX29wX20xMDQiLCJpc3MiOiJodHRwczovL2NsZXJrLnRlc3QuYWdlbnRzZmxlZXQubmV0IiwiYXVkIjoiaHR0cHM6Ly9hcGkuYWdlbnRzZmxlZXQubmV0IiwiZXhwIjo0MTAyNDQ0ODAwLCJzY29wZXMiOiJydW5uZXI6ZW5yb2xsIHJ1bm5lcjpyZWFkIHJ1bm5lcjp3cml0ZSBzdHJlYW06cmVhZCBtb2RlbDphZG1pbiBwbGF0Zm9ybS1rZXk6YWRtaW4gdGVtcGxhdGU6YWRtaW4gd29ya3NwYWNlOmFueSIsIm1ldGFkYXRhIjp7InRlbmFudF9pZCI6IjAxOTViNGJhLThkM2EtN2YxMy04YWJjLTJiM2UxZTBhNmYwMSIsIndvcmtzcGFjZV9pZCI6IjAxOTViNGJhLThkM2EtN2YxMy04YWJjLTJiM2UxZTBhNmYxMSJ9fQ.AC0Hp85X1yVY8JMKwc9ExtpoZjHaeiSK8qD9yLMTJAADvng9xZiFvRDyzdP6Rf50lTuBSYRznGygU6Vc5LPJtAtDn2y_W_pK_tLIsFEI8F3Fw6Bpxz28nrxgNbVVL3WqksAgC4E0_PuaTW5MW0SPM0n907c4Fe66qcK9wccucjNQr79J0sl1jZG-O1quzUicAbiDVuEhI90NMMPuSxnYVJd6G_U9cXoTU2t1OqbI_o8iPOv_No1ua36YDUpco7Oa9d4z67qM-QU1xLtSSW6MnRsMeMxcUfddgekef4n_zWiRQQtlUWgARrclURiM4L7rA1959ekYyW5DAc72hL6-nQ";
/// Persona — see scopes in the module header. Minted by scripts/mint-scope-personas.mjs.
pub const NO_TENANT =
    "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InRlc3Qta2lkLXN0YXRpYyJ9.eyJzdWIiOiJ1c2VyX20xMV8wMDYiLCJpc3MiOiJodHRwczovL2NsZXJrLnRlc3QuYWdlbnRzZmxlZXQubmV0IiwiYXVkIjoiaHR0cHM6Ly9hcGkuYWdlbnRzZmxlZXQubmV0IiwiZXhwIjo0MTAyNDQ0ODAwLCJzY29wZXMiOiJmbGVldDphZG1pbiBjcmVkZW50aWFsOndyaXRlIGFwaWtleTphZG1pbiBmbGVldGtleTp3cml0ZSBncmFudDp3cml0ZSBjb25uZWN0b3I6d3JpdGUgYmlsbGluZzpyZWFkIGFwcHJvdmFsOnJlc29sdmUgd29ya3NwYWNlOmFkbWluIHRlbXBsYXRlOndyaXRlIiwibWV0YWRhdGEiOnt9fQ.QwFlT0s6SqFXUJcf-aL8oCrd01Bi4cq7qf_QlIGv1-gTHg7BUP8iU_jif-DpjaX1rgsEGtM4nydywL0MgG8_Ii76O4fsygBMdGxGAo5hmCcAaR0iBEiWyc7mpfP4ciYrZQG-H0n8GPXjMqptGr9pK5HdTZ-jQxMbvtnOa6EYR0nV6TEAK24t3An64eWBFuEFcO9tA7XXqiemhJrqxxbZNnVmDc43gf0k5jGf5qhsHi8eXk5w9ZMv6scYmh5tFn5HySX-_CPuQUbhZ0eF4pzTYd1ayaXonRWkaxGxTcZrRCkUqw7WM7bg_CPTCnQ94OM_ExyM3ngKqCJ-oASfBeNf6w";
