//! Shared offline auth fixtures for the integration suite — ONE committed
//! keypair + a fixed set of PERSONAS, so the JWKS can't drift per-file and a
//! scope change is a one-line edit in scripts/mint-scope-personas.mjs.
//!
//! Personas (scope sets):
//!   VIEWER          fleet:read
//!   OPERATOR        fleet:write secret:read
//!   TENANT_ADMIN    fleet:admin secret:write apikey:admin fleetkey:write grant:write connector:write billing:read approval:resolve workspace:admin library:write
//!   PLATFORM_ADMIN  runner:enroll runner:read runner:write stream:read model:admin platform-key:admin platform-library:write workspace:any
//!   NO_TENANT       fleet:admin secret:write apikey:admin fleetkey:write grant:write connector:write billing:read approval:resolve workspace:admin library:write
//!
//! Regenerate with: node scripts/mint-scope-personas.mjs --apply

pub const ISSUER = "https://clerk.test.agentsfleet.net";
pub const AUDIENCE = "https://api.agentsfleet.net";
pub const JWKS =
    \\{"keys":[{"kty":"RSA","n":"w2oFSV7rG1xjHczXGPcK1xDj1i5FYceHf8ZgBuM4czvrTQ70eQLVrArD5pPL0WFyE9WGQC8UjOumKUNctO2MPIW7q0ncnFXzDDczkHeTnxPDyPJX5yeA6GdEbkGm0HkCrPFFqdf69lpzuuEsCwd1rLX_Iq7WNoLYJ4AysF5Ypcd4jVRw4LhseQZ4KcME5gpb-EvOS5Lo6z_T2ZEiktVW7YE_OVKWOlJ-9ot1NCfCufH1nV1q3rN5vAngijxzxFRoWsdhuuHdzOH8xJiYTidSTFiLMKVMxunMqrSTdJqwhLyGkBYJvH_xwCmGAtKA0-uIeO-3eBYDwS1Fs2LgzegdDw","e":"AQAB","kid":"test-kid-static","use":"sig","alg":"RS256"}]}
;

/// Persona — see scopes in the module header. Minted by scripts/mint-scope-personas.mjs.
pub const VIEWER =
    "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InRlc3Qta2lkLXN0YXRpYyJ9.eyJzdWIiOiJ1c2VyX3Rlc3QiLCJpc3MiOiJodHRwczovL2NsZXJrLnRlc3QuYWdlbnRzZmxlZXQubmV0IiwiYXVkIjoiaHR0cHM6Ly9hcGkuYWdlbnRzZmxlZXQubmV0IiwiZXhwIjo0MTAyNDQ0ODAwLCJzY29wZXMiOiJmbGVldDpyZWFkIiwibWV0YWRhdGEiOnsidGVuYW50X2lkIjoiMDE5NWI0YmEtOGQzYS03ZjEzLThhYmMtMmIzZTFlMGE2ZjAxIiwid29ya3NwYWNlX2lkIjoiMDE5NWI0YmEtOGQzYS03ZjEzLThhYmMtMmIzZTFlMGE2ZjExIn19.BNAMRRdD7GPXBQBGeCZbYV2cOVrnNDIlwhq0TKWv7XRfcRO-7RUJ-L1wYNrTWQTAWFg13t28gq1a1IdrPiFfVq3fce5A2RkaA15EH7Lqd65WHtZ3ydAuLpVstKQQIm_VdMtDdfBGY2p5p7FlcJ8MVAtLkcTDqnkyvb_aJZaR7oSkMbhizPKx5B7GUSOuz5xR8sMJEbkSSavU6_EiLQlrIIRu71bIQ-gG_QzjIFMC4hBkBQJKTWJ44AfTbjOy8K58qLRvWx_Aox0OKs5MY30InhDFqcbaE8H0C6heOuiSGP0BjiCs5rNpGiwFG4FlzZF6bIWdYkH_uvuc1OYxOk0sfw";
/// Persona — see scopes in the module header. Minted by scripts/mint-scope-personas.mjs.
pub const OPERATOR =
    "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InRlc3Qta2lkLXN0YXRpYyJ9.eyJzdWIiOiJ1c2VyX3Rlc3QiLCJpc3MiOiJodHRwczovL2NsZXJrLnRlc3QuYWdlbnRzZmxlZXQubmV0IiwiYXVkIjoiaHR0cHM6Ly9hcGkuYWdlbnRzZmxlZXQubmV0IiwiZXhwIjo0MTAyNDQ0ODAwLCJzY29wZXMiOiJmbGVldDp3cml0ZSBzZWNyZXQ6cmVhZCIsIm1ldGFkYXRhIjp7InRlbmFudF9pZCI6IjAxOTViNGJhLThkM2EtN2YxMy04YWJjLTJiM2UxZTBhNmYwMSIsIndvcmtzcGFjZV9pZCI6IjAxOTViNGJhLThkM2EtN2YxMy04YWJjLTJiM2UxZTBhNmYxMSJ9fQ.XP59P9-hrasSK3vkmKStruZvhUjwYJcWVtpzT_jMbu__1xXyJV65rrEbFgvogOOdHjWYEcbS50BsQTKNXA-24vnymcfIFkYMZslxEj1r6vlUJc7KH-nh08MzJ1sOr4TH09ANH6kHeVwfxToujihTJ6lVbkuIO0X33-K0lVh4dQJBJzE2yU3JkczaSqLBPujxwVPwaXPXafPdGG7OmIDEmeuGFBIGbJKZNirOHQHMQm35ZV_7U4ouCB-Kq4S-6DPahFyvdZ2mno-_NUUOBuVnty6Czs3pv8o3wAd16415cHcJ6Ymxzr_zhFLtyDvL4Q2-Ws9VOx3LdGDjpVNiF0g8vQ";
/// Persona — see scopes in the module header. Minted by scripts/mint-scope-personas.mjs.
pub const TENANT_ADMIN =
    "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InRlc3Qta2lkLXN0YXRpYyJ9.eyJzdWIiOiJ1c2VyX3Rlc3QiLCJpc3MiOiJodHRwczovL2NsZXJrLnRlc3QuYWdlbnRzZmxlZXQubmV0IiwiYXVkIjoiaHR0cHM6Ly9hcGkuYWdlbnRzZmxlZXQubmV0IiwiZXhwIjo0MTAyNDQ0ODAwLCJzY29wZXMiOiJmbGVldDphZG1pbiBzZWNyZXQ6d3JpdGUgYXBpa2V5OmFkbWluIGZsZWV0a2V5OndyaXRlIGdyYW50OndyaXRlIGNvbm5lY3Rvcjp3cml0ZSBiaWxsaW5nOnJlYWQgYXBwcm92YWw6cmVzb2x2ZSB3b3Jrc3BhY2U6YWRtaW4gdGVtcGxhdGU6d3JpdGUiLCJtZXRhZGF0YSI6eyJ0ZW5hbnRfaWQiOiIwMTk1YjRiYS04ZDNhLTdmMTMtOGFiYy0yYjNlMWUwYTZmMDEiLCJ3b3Jrc3BhY2VfaWQiOiIwMTk1YjRiYS04ZDNhLTdmMTMtOGFiYy0yYjNlMWUwYTZmMTEifX0.hv6GDkByYTCiZaufe64Ej8xNBWZ-lY1dwG39Dj5TyNUHqNElStifqU6K28StBATDDR31sM-xQKd02npar3mCZuUrQxccDIA7XKLVOVJHFfLZWnYzQ7JLDqXZ68N8MGItUuKo1i4FzLrGH4S2tQ9eHgE82sb6M1sD-oTG0ItEywnYxUTtvZXyjczVJeuUQcALXF7JWAq3wHBY2FEiMyhsDrCKzM1vAhjlibZhCsBdEtQJmSxFGMRoWgbKDwW8o0XfeZgK6Y8bSsuIDQxRcA4pSSdUrzzpzptxukMcfzr6arYlrcUhW9zwB-PWoC63yAJ_tgiqptPnnQuZgSsLGJyrCQ";
/// Persona — see scopes in the module header. Minted by scripts/mint-scope-personas.mjs.
pub const PLATFORM_ADMIN =
    "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InRlc3Qta2lkLXN0YXRpYyJ9.eyJzdWIiOiJ1c2VyX29wX20xMDQiLCJpc3MiOiJodHRwczovL2NsZXJrLnRlc3QuYWdlbnRzZmxlZXQubmV0IiwiYXVkIjoiaHR0cHM6Ly9hcGkuYWdlbnRzZmxlZXQubmV0IiwiZXhwIjo0MTAyNDQ0ODAwLCJzY29wZXMiOiJydW5uZXI6ZW5yb2xsIHJ1bm5lcjpyZWFkIHJ1bm5lcjp3cml0ZSBzdHJlYW06cmVhZCBtb2RlbDphZG1pbiBwbGF0Zm9ybS1rZXk6YWRtaW4gcGxhdGZvcm0tdGVtcGxhdGU6d3JpdGUgd29ya3NwYWNlOmFueSIsIm1ldGFkYXRhIjp7InRlbmFudF9pZCI6IjAxOTViNGJhLThkM2EtN2YxMy04YWJjLTJiM2UxZTBhNmYwMSIsIndvcmtzcGFjZV9pZCI6IjAxOTViNGJhLThkM2EtN2YxMy04YWJjLTJiM2UxZTBhNmYxMSJ9fQ.Gd9gn_uwlyZ51ArldHcgIBs79xYpaOXmiMXVtArqmKMfegZtGdqoRfyVPNosX5CLnMGnorSlYBKlXZWXokoxkDCMCMxl7jmZ_U-5If8QzF4-tyq-0KpyXFiCWc9nKTr25_4QWWCJYwcS-i-htvqNyHxsxTXKYo9LQ5K0eW8kmPg5xObZIZ8wdpT8jPLniUrUeKXayhjY2BzhJLW26NlhrG15jI3IbNiiaD-980ANdBPVIDgiq3nj-qjSXuv-AJWt6wgnigLfK8RBpm411uLuXOWw7E7TSiYPnZdCwUB60V98eay97mtuh96A4DhOAtS24N7jQ9DwEr_U3gxttsAuoA";
/// Persona — see scopes in the module header. Minted by scripts/mint-scope-personas.mjs.
pub const NO_TENANT =
    "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InRlc3Qta2lkLXN0YXRpYyJ9.eyJzdWIiOiJ1c2VyX20xMV8wMDYiLCJpc3MiOiJodHRwczovL2NsZXJrLnRlc3QuYWdlbnRzZmxlZXQubmV0IiwiYXVkIjoiaHR0cHM6Ly9hcGkuYWdlbnRzZmxlZXQubmV0IiwiZXhwIjo0MTAyNDQ0ODAwLCJzY29wZXMiOiJmbGVldDphZG1pbiBzZWNyZXQ6d3JpdGUgYXBpa2V5OmFkbWluIGZsZWV0a2V5OndyaXRlIGdyYW50OndyaXRlIGNvbm5lY3Rvcjp3cml0ZSBiaWxsaW5nOnJlYWQgYXBwcm92YWw6cmVzb2x2ZSB3b3Jrc3BhY2U6YWRtaW4gdGVtcGxhdGU6d3JpdGUiLCJtZXRhZGF0YSI6e319.lw1Glk-UXY2MrFxLDIwYDmcmYU9u9Vb3kjJuDvH-I9jDsVmOc-0g_g8y7sjYWo7pdzrSmCeo9yTTc5yfmFPsAnXv4HIVVP3pflgBhATbFruG6Ue0G0d7WJBk3ID640CNlhw1EmTqpH43kndK9U810X7RUbef4iEDRFOlqlKwF5nKiCy8Kai363Ttp1uq1HVLptnVX_8RceCmANq5gmXLXpPQtASjGOW-EALs4iR7zTsItP9q2fm6Q1_-a_j1VXk-E6QV0YvZgUtip6OU8MuuVJH4CAYEW76r1MYs79XKOMoHYYqWmvNh_phyl0901hSOzI2Gusr2TLjRNueLJDqwcg";
